### ISSUE TITLE
Does it mean the user I set have no privileges to get  AD's user attributes?

### ISSUE THREAD

**Issue by brucemiao2** [etianen/django-python3-ldap#100]
INFO 2017-08-21 08:48:45,329 [ LDAP connect succeeded]  /usr/local/lib/python3.4/site-packages/django_python3_ldap/ldap.py  connection 182
WARNING 2017-08-21 08:48:45,332 [ LDAP user attributes empty]  /usr/local/lib/python3.4/site-packages/django_python3_ldap/ldap.py  _get_or_create_user 41

**Comment by etianen** [comment]
Possibly. It means that the request for user data returned no attributes. I
guess permissions might be the cause of that.
