### ISSUE TITLE
Always returns LDAPInvalidCredentials with true username and password

### ISSUE THREAD

**Issue by notvishwanth** [etianen/django-python3-ldap#101]
I don't know if I'm doing it right, because i'm fairly new to LDAP and django.

Here's my settings file:
```
# The URL of the LDAP server.
LDAP_AUTH_URL = "url"

# The LDAP search base for looking up users.
LDAP_AUTH_SEARCH_BASE = "OU=someOU,DC=someDC,DC=someDC,DC=net"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
# A tuple of django model fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

# Path to a callable that takes a dict of {ldap_field_name: value},
# returning a list of [ldap_search_filter]. The search filters will then be AND'd
# together when creating the final search filter.
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "app.views.search_filter"
```

And my search_filter function:
```
def search_filter(ldap_fields):
    # Add in simple filters.
    ldap_fields["uid"] = "uid="
    # Call the base format callable.
    search_filters = format_search_filters(ldap_fields)
    # All done!
    return search_filters
```
Again, I dont know if this is the right thing, but I have a LDAP working code(Python 2.7 and non Django) for reference, If you could look at that and tell me where I should make changes for making the Error go away, that would be very helpful,,

```
username=data['username'].value
	username=username+"@somecompany.net"
	password=data['password'].value
	ldap_server="url"
	base_dn="OU=someOU,DC=someDC,DC=someDC,DC=net"
	connect=ldap.open(ldap_server)
	connect.bind_s(username,password)
	search_filter="uid="+username
	result=connect.search_s(base_dn,ldap.SCOPE_SUBTREE,search_filter)
	print 1
	connect.unbind_s()
```
Please help, thanks

**Comment by etianen** [comment]
This might work:

LDAP_AUTH_URL = "url"
LDAP_AUTH_SEARCH_BASE = "OU=someOU,DC=someDC,DC=someDC,DC=net"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "somecompany.net"
LDAP_AUTH_FORMAT_USERNAME =
"django_python3_ldap.utils.format_username_active_directory_principal"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

I don't think you need to define custom search filters.

**Comment by michaelcalve** [comment]
I'm getting this same error, as my django server is trying to use the user's login credentials as auth creds for the ldap server!

**Comment by etianen** [comment]
There is almost certain a setting to fix this. Keep fiddling!

LDAP error messages are rubbish, sadly.

**Comment by michaelcalve** [comment]
What settings? Is it possible to bind to LDAP using anyone in a certain groups' AD creds?

**Comment by michaelcalve** [comment]
Figured out that I had to use the CN which is "first last" not the username which is "first.last" :)
