### ISSUE TITLE
Authenticate against auth_user if not in LDAP

### ISSUE THREAD

**Issue by Houldern** [etianen/django-python3-ldap#104]
Hey

Thanks for the work you've put in this project, it has been really usefull
to me in an assignment at work.

Was wondering though, if there is any easy way to make the module
authenticate with a user that is not found with LDAP but exists in auth_user in the
Django database? Would like to have an admin-user for the db but it should not exist
in AD.

Cheers

EDIT:
Sry for not looking good enough, it was a closed issue from before.

Answer:

AUTHENTICATION_BACKENDS = [
'django_python3_ldap.auth.LDAPBackend',
'django.contrib.auth.backends.ModelBackend'
]

**Comment by etianen** [comment]
Easy!

Instead of this setting:

AUTHENTICATION_BACKENDS = ("django_python3_ldap.auth.LDAPBackend",)

Use this:

AUTHENTICATION_BACKENDS = (
    "django_python3_ldap.auth.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
)

Django tries the authentication backends in order. If the user isn't found
in LDAP, it'll try in the database.

Pretty sweet! :D

**Comment by Houldern** [comment]
Yeah, thanks!
