### ISSUE TITLE
LDAP user lookup failed

### ISSUE THREAD

**Issue by russell-phe** [etianen/django-python3-ldap#107]
Hi, thanks for all the work in creating this package, really appreciated.

I'm in the process of implementing LDAP for my project and I am coming unstuck trying to return a user profile from the LDAP server. The server logs are saying that the connection is being made successfully, but it is failing to bind during the get_user function of ldap.py. 

This is my settings.py ldap options:

```
AUTHENTICATION_BACKENDS = (
    "django_python3_ldap.auth.LDAPBackend",
    'django.contrib.auth.backends.ModelBackend',
)

LDAP_AUTH_URL = "ldap://server.org.thing.uk:389"

LDAP_AUTH_USE_TLS = False

LDAP_AUTH_SEARCH_BASE = "OU=User Objects - Employee Accounts,OU=Administrated Objects,DC=org,DC=thing,DC=uk"

LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"

LDAP_AUTH_USER_FIELDS = {
    "username": "uid",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "ORG"

LDAP_AUTH_CONNECTION_USERNAME = "Perc.Auth.SRV"
LDAP_AUTH_CONNECTION_PASSWORD = "************"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
```

If I print out the self._connection.search from get_user in ldap.py, I get the following:

`<bound method Connection.search of Connection(server=Server(host='server.org.thing.uk', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], get_info='NO_INFO', mode='IP_V6_PREFERRED'), user='ORG\\Perc.Auth.SRV', p
assword='**********', auto_bind='NO_TLS', version=3, authentication='SIMPLE', client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=False, lazy=False, raise_exceptions=True, fast_decoder=True, auto_range=True, return_empty_attributes=T
rue)>
`
However, this does not trigger the if statement in get_user and therefore does not complete the lookup. Any help would be appreciated!

**Comment by etianen** [comment]
Can I see the exact server logs?

**Comment by russell-phe** [comment]
Hi, I don't have access to the server logs, but the person who does showed them to me earlier, with this being an example of the successful logins that were showing:
```
An account was successfully logged on.
 
Subject:
                Security ID:                            SYSTEM
                Account Name:                    SERVER$
                Account Domain:                 ORG
                Logon ID:                               0x3E7
 
Logon Type:                                          3
 
Impersonation Level:                           Impersonation
 
New Logon:
                Security ID:                            ORG\Firstname.Surname
                Account Name:                    Firstname.Surname
                Account Domain:                 ORG
                Logon ID:                               0x65E1A88A
                Logon GUID:                          {00000000-0000-0000-0000-000000000000}
 
Process Information:
                Process ID:                             0x240
                Process Name:                      C:\Windows\System32\lsass.exe
 
Network Information:
                Workstation Name:              SERVER
                Source Network Address:    ************
                Source Port:                           60990
 
Detailed Authentication Information:
                Logon Process:                     Advapi  
                Authentication Package:     MICROSOFT_AUTHENTICATION_PACKAGE_V1_0
                Transited Services:                -
                Package Name (NTLM only):             -
                Key Length:                           0
 
This event is generated when a logon session is created. It is generated on the computer that was accessed.
 
The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.
 
The logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).
 
The New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.
 
The network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.
 
The impersonation level field indicates the extent to which a process in the logon session can impersonate.
 
The authentication information fields provide detailed information about this specific logon request.
                - Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.
                - Transited services indicate which intermediate services have participated in this logon request.
                - Package name indicates which sub-protocol was used among the NTLM protocols.
                - Key length indicates the length of the generated session key. This will be 0 if no session key was requested. 
```
There are  4 events triggered for each login attempt - logon Firstname.Surname user, logon Perc.Auth.SRV server, log off user, log off server. From the server end, everything seems to be working fine. I am getting a `LDAP connect succeeded` printed before `LDAP user lookup failed` on every connect. 
If I attempt to print self._connect.response, I get an empty list.

**Comment by etianen** [comment]
If the user lookup is failing, I'd check that the LDAP_AUTH_SEARCH_BASE and
LDAP_AUTH_OBJECT_CLASS are correct.

**Comment by russell-phe** [comment]
I've had confirmation that those are correct from the sysadmin. 

I have had a deeper look at what is going on. The `get_user` function in ldap.py is failing because the connection.response list is returning []. The connection search being passed in is:

```
<bound method Connection.search of Connection(server=Server(host='server.org.thing.uk', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], get_info='NO_INFO', mode='IP_V6_PREFERRED'), user='ORG\\Perc.Auth.SRV', p
assword='*************', auto_bind='NO_TLS', version=3, authentication='SIMPLE', client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=False, lazy=False, raise_exceptions=True, fast_decoder=True, auto_range=True, return_empty_attributes=T
rue)>
```

Taking a look further into the connection process in the `ldap3` package with the `_get_responses` gets called, and `self` is defined as:
```
{'_outstanding': {2: {'authentication': {'sasl': None,
                                         'simple': '[hD^C>+_DdN#.d-Ix'},
                      'controls': None,
                      'name': 'PHE\\Perc.Auth.SRV',
                      'type': 'bindRequest',
                      'version': 3}},
 '_referrals': [],
 'can_stream': False,
 'connection': Connection(server=Server(host='server.org.thing.uk', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], get_info='NO_INFO', mode='IP_V6_PREFERRED'), user='ORG\\Perc.Auth.SRV', password='************', auto_bind='NO_TLS', version
=3, authentication='SIMPLE', client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=False, lazy=False, raise_exceptions=True, fast_decoder=True, auto_range=True, return_empty_attributes=True),
 'no_real_dsa': False,
 'pooled': False,
 'referral_cache': {},
 'socket_size': 4096,
 'sync': True}

```
This in turn calls `self.receiving()`, which returns 1 response, which looks like this once decoded:

`{'controls': None, 'payload': [(0, False, 10, 0), (0, False, 4, b''), (0, False, 4, b'')], 'messageID': 2, 'protocolOp': 1}
`

and it is returned as a message in the form of a byte string:`b'0\x84\x00\x00\x00\x10\x02\x01\x04e\x84\x00\x00\x00\x07\n\x01\x00\x04\x00\x04\x00'`, which is used as a response.

This all looks ok, but when it comes to this being dealt with in the responses part of `_get_responses`, the `ldap_resp` does not contain a message (decoded): `{'type': 'searchResDone', 'referrals': None, 'description': 'success', 'result': 0, 'dn': '', 'message': ''}`. 

Any suggestions as to why this is?

Thanks.

**Comment by etianen** [comment]
To confirm, your user records in LDAP have a "uid" field to represent the
username?

Fundamentally, the search query being sent by django-python3-ldap is giving
no results, which implies heavily that some aspect of the search query is
not correct for your LDAP server. Maybe try commenting out bits of the
search() call in the get_user() method until you get some results? That way
you'll be able to narrow down which setting is incorrect.

**Comment by MNicholasPro** [comment]
I want to know how to solve this problem very much!!! And I met this problem, too.I have spent two days to finding out the answer.....

**Comment by MNicholasPro** [comment]
I want to know how to solve this problem very much!!! And I met this problem, too.I have spent two days to finding out the answer.....:
Django 2.0.5
python 3.6.4

**Comment by freezed** [comment]
Same error for me here trying to connect a local _Microsoft Active Directory ©®_.
Solved with the help of my domain administrator with :

`LDAP_AUTH_OBJECT_CLASS` = "person"`

Thx for this brilliant package !
