### ISSUE TITLE
LDAP user lookup failed

### ISSUE THREAD

**Issue by chamunzira** [etianen/django-python3-ldap#110]
Hie. when i run the python manage.py ldap_sync_users command i get the following response
LDAP user lookup succeeded
Synced
My challenge is that there is no data being populated in the models after i sync the user. What could i be missing?

When i then try to login in Django Admin i then get the following response
LDAP connect succeeded
LDAP user lookup failed

**Comment by etianen** [comment]
Your LDAP search base setting, or object class setting, is almost certainly
incorrect.

**Comment by chamunzira** [comment]
So definitely connection to the Active directory is there but my search base and the object class is wrong

**Comment by chamunzira** [comment]
Thank you very much the object class was the problem. i can now login successfully

**Comment by etianen** [comment]
Glad to help!

**Comment by DVJT** [comment]
so what did you have to set the "LDAP_AUTH_OBJECT_CLASS" to ?

**Comment by chamunzira** [comment]
LDAP_AUTH_OBJECT_CLASS = "user"

i did this
