### ISSUE TITLE
LDAP connect succeeded but DAPInvalidCredentialsResult - 49 - invalidCredentials

### ISSUE THREAD

**Issue by elshadsu** [etianen/django-python3-ldap#111]
Hi, 
I'm trying to use django-python3-ldap but I can't

I received this result, as I know it menas success and everything is ok
python3.6 manage.py ldap_sync_users
LDAP connect succeeded

But i can't login with my own LDAP user (company username) and password because this error was occur
[12/Jan/2018 00:16:26] "GET /login/?next=/mainpage/ HTTP/1.1" 200 7175
**LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839 - bindResponse - None**
[12/Jan/2018 00:16:39] "POST /login/ HTTP/1.1" 200 7246

It's my setting.py
===============================================
import ldap
from django_auth_ldap.config import LDAPSearch

AUTHENTICATION_BACKENDS = [
'django_python3_ldap.auth.LDAPBackend',
'django.contrib.auth.backends.ModelBackend',
]

LDAP_AUTH_URL = "ldap://url_here:port"
LDAP_AUTH_USE_TLS = False
LDAP_AUTH_SEARCH_BASE = "dc=company,dc=com" 
LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"
LDAP_AUTH_USER_FIELDS = {"username": "uid", "first_name": "givenName", "last_name": "sn", "email": "mail",}
LDAP_AUTH_USER_LOOKUP_FIELDS = ('username',)
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"
LDAP_AUTH_CONNECTION_USERNAME = 'my_ldap_username'
LDAP_AUTH_CONNECTION_PASSWORD = 'my_ldap_password'
LDAP_AUTH_CONNECT_TIMEOUT = None
LDAP_AUTH_RECEIVE_TIMEOUT = None
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

Please advice

**Comment by etianen** [comment]
After running ldap_sync_users, did any users actually get imported into
your database?

It's also possible that you need to change one of these settings to match
what your server is expecting:

   - LDAP_AUTH_FORMAT_USERNAME
   - LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN
   - LDAP_AUTH_OBJECT_CLASS
   - LDAP_AUTH_SEARCH_BASE

Unless you know exactly the settings your server is expecting, however, it
basically comes down to trial and error. There are many settings to get
wrong, and the server error messages are useless. I wrote this library, so
you'd think I'd understand LDAP, but last time I tried to integrate
MediaWiki with my company LDAP it too a whole day to configure things
correctly!

**Comment by elshadsu** [comment]
Thank you very much. I did some changes in setting.py

```
LDAP_AUTH_OBJECT_CLASS = "user"
LDAP_AUTH_USER_FIELDS = {"username": "sAMAccountName",
                         "first_name": "givenName", "last_name": "sn", "email": "mail",}
LDAP_AUTH_USER_LOOKUP_FIELDS = ('username',)
```

and run
python3.6 manage.py ldap_sync_users

All users from LDAP upload to django and i can see them through admin panel but one problem didn't solve

When i try edit any user i see to give the user any rights
Password: No password set.

and for that reason selected user can't login into site

**Comment by etianen** [comment]
The password isn't saved in the user model. It's checked on the LDAP server
on each login.

If you can't login, then the LDAP bind isn't working. You probably want to
look at:

   - LDAP_AUTH_FORMAT_USERNAME
   - LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN

**Comment by elshadsu** [comment]
You were right. I incorrectly inserted the parameters

Thanks a lot

**Comment by elshadsu** [comment]
Hello again
Tell me please

How to sync all employees with inactive status
I mean that all users which I see through the admin panel should have an inactive status

**Comment by etianen** [comment]
You'll want to override the LDAP_AUTH_CLEAN_USER_DATA setting.

https://github.com/etianen/django-python3-ldap#available-settings

Something like:

``` py
# settings.py

LDAP_AUTH_CLEAN_USER_DATA = "path.to.your.module.clean_user_data

# path/to/your/module.py

def clean_user_data(data)::
    data["is_active"] = False
    return data
```

**Comment by komaxko** [comment]
Hi there,
I have a problem: can't bind and connect to LDAP SERVER.

my settings.py:

AUTHENTICATION_BACKENDS = (
    'django_python3_ldap.auth.LDAPBackend',
    # 'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)



# The URL of the LDAP server.
LDAP_AUTH_URL = "ldap://server.domain.com:389"

# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = False

# The LDAP search base for looking up users.
LDAP_AUTH_SEARCH_BASE = "ou=users,dc=domain,dc=com"

# The LDAP class that represents a user.
# LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"
LDAP_AUTH_OBJECT_CLASS = "user"

# User model fields mapped to the LDAP
# attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# A tuple of django model fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

# Path to a callable that takes a dict of {model_field_name: value},
# returning a dict of clean model data.
# Use this to customize how data loaded from LDAP is saved to the User model.
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

# Path to a callable that takes a user model and a dict of {ldap_field_name: [value]},
# and saves any additional user relationships based on the LDAP data.
# Use this to customize how data loaded from LDAP is saved to User model relations.
# For customizing non-related User model fields, use LDAP_AUTH_CLEAN_USER_DATA.
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

# Path to a callable that takes a dict of {ldap_field_name: value},
# returning a list of [ldap_search_filter]. The search filters will then be AND'd
# together when creating the final search filter.
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

# Path to a callable that takes a dict of {model_field_name: value}, and returns
# a string of the username to bind to the LDAP server.
# Use this to support different types of LDAP server.
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

# For user-principal-name formats (e.g. "user@domain.com"):#
# LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"
# LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "domain.com"


# Sets the login domain for Active Directory users.
# LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = None


LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "domain.com"

# The LDAP username and password of a user for querying the LDAP database for user
# details. If None, then the authenticated user will be used for querying, and
# the `ldap_sync_users` command will perform an anonymous query.
# LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_USERNAME = "username"
# LDAP_AUTH_CONNECTION_PASSWORD = None
LDAP_AUTH_CONNECTION_PASSWORD = "*******"

# Set connection/receive timeouts (in seconds) on the underlying `ldap3` library.
LDAP_AUTH_CONNECT_TIMEOUT = None
LDAP_AUTH_RECEIVE_TIMEOUT = None



What's the problem?

**Comment by etianen** [comment]
Hi @komaxko. In future, it might be best to open a new issue, rather than re-using an unrelated one! 😄 

Please enable logging for your application:

https://github.com/etianen/django-python3-ldap#logging

This will give you much more detail about the login process, allowing you to pin down what's going wrong.

**Comment by komaxko** [comment]
Sorry, thought that I have the same problem and rather comment here and not open new issue)

For the moment I have synced users from AD to local BD, but the passwords didn't sync (blank filds) and after i've granted admin and staff in admin to user i can't login to admin as that user

**Comment by etianen** [comment]
No worries!

The passwords never sync - they're securely stored in LDAP.

Enable logging, and let me know what errors you get.

**Comment by komaxko** [comment]
Thank's a lot for a quick response!
Now it works perfectly! 

Question: if any user in Active Directory has changed password do I need to sync db again? or doest it make a bind and sync pass for a user any time user logs in?

**Comment by komaxko** [comment]
And is there any possibility to get groups that AD user is in?

**Comment by etianen** [comment]
The user model is synced on every login, so that's all taken care of.

To sync groups, there is an example of some code on this issue:

https://github.com/etianen/django-python3-ldap/issues/74#issuecomment-360457152
