### ISSUE TITLE
django-python3-ldap Search Users belonging to Specific Group in Active Directory

### ISSUE THREAD

**Issue by cameronwtaylor** [etianen/django-python3-ldap#113]
I have `django-python3-ldap` included in my Django project, and I have it pointed at an Active Directory server. It connects to the AD server and returns a the username, first name, and hashed password to the `auth_user` table. How do I limit the search to only users in a specific AD group? 

Here are the relevant settings:

    LDAP_AUTH_SEARCH_BASE = "OU=******,DC=ad,DC=******,DC=org"
    LDAP_AUTH_USER_FIELDS = {
         "username": "samaccountname",
         "first_name": "givenname",
         "last_name": "surname",
         "email": "EmailAddress",
    }
    LDAP_AUTH_OBJECT_CLASS = "User"
    LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
    LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
    LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "AD"
    LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

I believe I need to use `LDAP_AUTH_FORMAT_SEARCH_FILTERS` to "and" conditions to the original search base, but I'm not sure exactly how to do so. I assume I need to write a custom `format_search_filter`, but I don't intuitively understand how it would cross-check with AD groups. Can I somehow check the `memberOf` field? 

**Update:** I now realize I didn't scroll down far enough in the documentation...so I have set up a custom function like this: 

    from django_python3_ldap.utils import format_search_filters

    def custom_format_search_filters(ldap_fields):
        ldap_fields["memberof"] = "TMPROD"
        search_filters = format_search_filters(ldap_fields)
        return search_filters

Unfortunately, this results in `LDAP user lookup failed`. I'm positive the group name is correct, and that I belong to the group.

**Comment by iannobile** [comment]
This may be a bit late, but I'm adding this here to help anyone who is still having trouble filtering by groups. To retrieve the group in Active Directory you need to use the following format:
`(memberOf=CN=GroupName,CN=Users,DC=example,DC=com)`

In python 2.7x, the format_search_filters converts the ldap_fields string to Unicode, replacing the `= `with its Unicode value `\\3D` This causes the lookup to fail. You can work around it by appending the AD string to the search_filter after the format_search_filter function is called.
e.g. `search_filters.append('(memberOf=CN=GroupName,CN=Users,DC=example,DC=com)')`

This will return all users that are members of GroupName in the domain OU you specified.
