### ISSUE TITLE
ldap_sync_users For Specific Group

### ISSUE THREAD

**Issue by cameronwtaylor** [etianen/django-python3-ldap#114]
Is it possible to run `ldap_sync_users` for a single LDAP (in this case Active Directory) group? I would imagine it would be similar to using `memberOf` to authenticate only users that belong to a specific group, but I'm not sure how to implement that. The only setting related to syncing is `LDAP_AUTH_SYNC_USER_RELATIONS`, and it points to an empty function. I'm only asking in the hypothetical because I'm worried about testing custom functions multiple times and risk bringing over too many users.

**Comment by etianen** [comment]
I think that you want to specify some custom user filters:

https://github.com/etianen/django-python3-ldap#custom-user-filters

**Comment by cameronwtaylor** [comment]
I have a custom user filter that looks almost identical to the example, and
it works to only authenticate people who are members of a specific group.
So the same custom user filter applies when I run ldap sync? Or does it
need modifications?

**Comment by etianen** [comment]
That filter also applies to ldap_sync_users.

Try it out! If you're really worried, do it on a copy of your database, and
delete the copy if too many users are pulled across.

**Comment by cameronwtaylor** [comment]
Unfortunately, we aren't currently allowed to make database copies. I will
give it a shot though - thank you for your help! And thank you for a
fantastic product. I agree that LDAP is a muddled mess, but this helps cut
through the mess a bit!
