### ISSUE TITLE
Are passwords encrypted over the network if TLS is set to True?

### ISSUE THREAD

**Issue by cameronwtaylor** [etianen/django-python3-ldap#116]
I have implemented this solution and integrated AD with my Django project. The project will be hosted on IIS as an intranet site that is served solely over http. I am attempting to decide between using this solution or Django's RemoteUserBackend. Using RemoteUserBackend with IIS and enabling Windows Authentication prevents clear text passwords from being sent across the network. Is the same thing happening when I set `LDAP_AUTH_USE_TLS = True` and my `LDAP_AUTH_URL` is pointing to an `LDAPS` domain controller? 

Is it more secure (all relative, I know) to use this solution or the IIS RemoteUserBackend solution?

**Comment by etianen** [comment]
If you are using an LDAPS server URL, or setting LDAP_AUTH_USE_TLS = True,
the network password should be sent encrypted over the network.

Theoretically, both solutions should give you the same security.
django-python3-ldap will give you better integration with the rest of your
Django application. RemoteUserBackend with IIS has probably received more
testing and auditing than django-python3-ldap.

**Comment by cameronwtaylor** [comment]
But that only encrypts the communication from web server to LDAPS server,
correct? So HTTPS would be required to encrypt communication (including
authentication creds) from browser to web server.

**Comment by etianen** [comment]
Yes, to encrypt browser -> web server, you need HTTPS. That's the case
whichever authentication backend you use.
