### ISSUE TITLE
LDAPNoSuchObjectResult

### ISSUE THREAD

**Issue by sokol-nastasya** [etianen/django-python3-ldap#123]
Hello! Can you help me with this problem?
#######################################
LDAP connect succeede
Internal Server Error: /admin/login/
ldap3.core.exceptions.LDAPNoSuchObjectResult: LDAPNoSuchObjectResult - 32 - noSuchObject - DC=SRDSC, DC=ORG - 0000208D: NameErr: DSID-0310020A, problem 2001 (NO_OBJECT), data 0, best match of: 'DC=SRDSC,DC=ORG'
- searchResDone - None

/settings.py

AUTHENTICATION_BACKENDS = [
    'django_python3_ldap.auth.LDAPBackend',
]

LDAP_AUTH_URL = "ldap://www.ldap.org:389"

LDAP_AUTH_USE_TLS = False

LDAP_AUTH_SEARCH_BASE = "ou=people,dc=srdsc,dc=org"

LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"

LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "srdsc.org"

LDAP_AUTH_CONNECTION_USERNAME = "archivetest"
LDAP_AUTH_CONNECTION_PASSWORD = ""

LDAP_AUTH_CONNECT_TIMEOUT = None
LDAP_AUTH_RECEIVE_TIMEOUT = None

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}  

What should I fix? 
Thank you

**Comment by etianen** [comment]
At a guess, your search base or object class setting is wrong.

Every LDAP server is it's own special snowflake, with many different
configuration options and terrible error messages.

**Comment by sokol-nastasya** [comment]
explain, why after the synchronization of users, I can not log in the user? How do I take user password? In the admin panel there are all users with AD.

**Comment by etianen** [comment]
I'm afraid that you're just going to have to experiment with settings. Any
error messages from the server are shown in the logs.

By the look of things, it's not finding users in your search base. Maybe
your search base could be more specific?

**Comment by sokol-nastasya** [comment]
apache error.log: 
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0c090334, comment: AcceptSecurityContext error, data 531, referer: http://www.####/account/login

but when I gave the command manage.py ldap_sync_users all users were synchronized and wrote that ldap was successfully connected.

**Comment by etianen** [comment]
The log message says invalid credentials.

If your user records exist in some sort of nested tree structure, then some
LDAP servers will allow you to sync the users, but won't allow you to
authenticate against them. Your users should all exist in a flat structure
at your LDAP_AUTH_SEARCH_BASE.

**Comment by gddr5** [comment]
raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPNoSuchObjectResult: LDAPNoSuchObjectResult - 32 - noSuchObject - DC=ХХХХХ,DC=ХХХХХХХ,DC=ХХХХХХ - 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:
        'DC=ХХХХХ,DC=ХХХХХХХ,DC=ХХХХХХ'
  - searchResDone - None


my domain is --subdomain.domain.org how do i use django-python3-ldap?

**Comment by michaeljarizala** [comment]
Just wanna share, I was having the same **_LDAPNoSuchObjectResult_** exception when running _ldap_sync_users_.

Realizing from **@etianen** advice, our records are defined within a nested tree struct **_ou=adn_** > **_ou=employee_** and our **LDAP_AUTH_SEARCH_BASE** was originally set to _"ou=adn,ou=employee,dc=edu,dc=au"_. I set it to the right definition as in _"ou=employee,ou=adn,dc=edu,dc=au"_ and it solved the issue. Luckily for me the mistake was just as small as improperly defining the search base lol

LDAP protocol is indeed very complicated as it is fun...
