### ISSUE TITLE
Improve logging with more details

### ISSUE THREAD

**Issue by bircow** [etianen/django-python3-ldap#126]
First of all I have to THANKS for this amazing library! It works perfectly. Only thing I would like to see is improved logging with more details.

E.g. log message `LDAP user lookup failed` is little bit useless if you don't know what user and what failed. Better message would be something like `LDAP lookup for user {username: 'foo'} failed`. Ideal to me seems to log also LDAP search expression with DEBUG severity that I could try in tools like ldapsearch.

Another hard to troubleshoot log message is _LDAP connect failed_ e.g. `LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1  - bindResponse - None`. Okay, invalid credentials but of which user?

**Comment by etianen** [comment]
I'd take a pull request to improve logging.

(Sorry for the late reply, work has been snowing me under!)
