### ISSUE TITLE
Improve "Active Directory support" in README

### ISSUE THREAD

**Issue by bircow** [etianen/django-python3-ldap#127]
I would like to consult improvement of "Active Directory support" section in README. I'm only very occasional Active Directory user therefore the following proposals needs to be reviewed by someone else with stronger AD knowledge.

### `sAMAccountName` is AD's equivalent to `uid` attribute
Thus for `AD LDAP_AUTH_USER_FIELDS` needs to be

    LDAP_AUTH_USER_FIELDS = {
        'username': 'sAMAccountName',
        'first_name': 'givenName',
        'last_name': 'sn',
        'email': 'mail',
    }

See https://msdn.microsoft.com/en-us/library/ms679635(v=vs.85).aspx.

### AD's object class of users is `user` instead of `inetOrgPerson`
Despite `inetOrgPerson` class exists in AD schema for compatibility reasons, regular users most usually have 'user' class instead.

    LDAP_AUTH_OBJECT_CLASS = 'user'

See https://social.technet.microsoft.com/wiki/contents/articles/20289.inetorgperson-class-in-active-directory.aspx.

**Comment by etianen** [comment]
My own knowledge of AD is also patchy. Adding these notes to the README
sounds like a good idea.

**Comment by bircow** [comment]
That would be great. I've just talked to my AD expert in my company and he confirmed both my proposals. Sharing these changes in README will help anyone who want use the lib against Active Directory.

**Comment by etianen** [comment]
I've updated the readme as you suggest. Thanks!
