### ISSUE TITLE
Question: request.user is returning anonymous user  

### ISSUE THREAD

**Issue by vibhash11** [etianen/django-python3-ldap#129]
For a lack of a better place, I am putting my question here. I am basically implementing a web app which will authenticate users present on the LDAP server as soon as the index page (home page) of my app will open i.e. there will be no login page. Everything else is working fine (ldap_sync_users can successfully fetch the data) but whenever i try to print request.user (in my views.py file), it displays 'AnonymousUser'. Is there something really obvious that I am missing?

**Comment by etianen** [comment]
I don't understand. How do you authenticate users with no login page?

**Comment by vibhash11** [comment]
Oh, I apoligise. I left some important information in the original question. We were actually allowing the user to give us a path to file using which we could extract their username and find if it is in the LDAP database. Obviously, not a nice method to do this so we are back to having a login page. Anyway, thanks for this awesome module. Without it I won't have been able to even create the basic structure of the web app. Thanks and sorry once again.
