### ISSUE TITLE
How to create user in LDAP through django project?

### ISSUE THREAD

**Issue by FabioNLima** [etianen/django-python3-ldap#131]
Hi, there

I am creating a django application for user registration.
After the user is created in django, it also has to be added in LDAP.
How can I do this?

**Comment by etianen** [comment]
The django-python3-ldap package only deals with authentication. Creating
users is another matter.

Take a look at the ldap3 package, which django-python3-ldap uses as a
backend. It'll let you interact with the LDAP server and add/remove records.
