### ISSUE TITLE
Invalid syntax error on python 3.7

### ISSUE THREAD

**Issue by radzhome** [etianen/django-python3-ldap#132]
Trying to use the package but get syntax error in connection when I do, on python 3.7, django 2.0.7

`    from .core.connection import Connection
  File "/Users/rwojcik/.local/share/virtualenvs/content-services-djongo-32J-jGSB/lib/python3.7/site-packages/ldap3/core/connection.py", line 55
    from ..strategy.async import AsyncStrategy
                        ^
SyntaxError: invalid syntax`

**Comment by etianen** [comment]
It looks to be an issue with the ldap3 library that django-python3-ldap
uses internally. I'd raise the issue with them.

**Comment by dex4er** [comment]
@etianen It is because this module uses older `ldap3` package. And after forced upgrade:

```
django-python3-ldap 0.11.1 has requirement ldap3==2.3, but you'll have ldap3 2.5 which is incompatible.
```

**Comment by lucacorti** [comment]
I'm using `master` which depends on ldap3 2.4.1 and it seems to work with python 3.7.

**Comment by etianen** [comment]
I've just released 0.11.2, which adds python 3.7 support.

**Comment by rspeed** [comment]
This seems fixed, though I would be good to specify a version *range* for dependencies. Since `ldap3` uses semantic versioning, it's safe to assume any version before 3.0 will remain compatible. So the dependency would be better written as `"ldap3>=2.5<3"` in `setup.py`.

**Comment by etianen** [comment]
It’s not safe to assume that. They break this library all the time.

I specify specific dependencies for a reason. :(
