### ISSUE TITLE
UserFilter (UID, CN - Validation)

### ISSUE THREAD

**Issue by Rohrdantz** [etianen/django-python3-ldap#133]
I am having trouble setting the module up for use with my company's LDAP. The issue arrises since the ldap does not match the username but instead the full name storen in a "cn" attribute . For the bind I would use:

`  cn= Name Givenname, ou=person, o=company, c=CA`

For other ldap plugins I had the option to use a search filter like so:
`  (&(objectClass=posixAccount)(uid=%s))`

which would then return the correct user.  I haven't figured out how to do this with neither the ldap3 module nor this django plugin directly. I did, however, manage to get a workaround running and was wondering if there is a better way to do it. I use ldap3 with the search filter to determine the user and extract the cn attribute, which I return for further handling to django-python3-ldap.

I created a function in utils (Edited with better idea from Gitea):
```python

def format_username_openldap_filter(model_fields):
    """
    Get an ldap distinguished name "DN" to bind with a user-filter
    """
    if settings.LDAP_AUTH_USER_FILTER:
        if settings.LDAP_AUTH_USE_TLS:
            auto_bind = ldap3.AUTO_BIND_TLS_BEFORE_BIND
        else:
            auto_bind = ldap3.AUTO_BIND_NO_TLS
        server = ldap3.Server(settings.LDAP_AUTH_URL,
                              allowed_referral_hosts=[("*", True)],
                              get_info=ldap3.NONE,
                              connect_timeout=settings.LDAP_AUTH_CONNECT_TIMEOUT)
        # Perform the user search
        with ldap3.Connection(server, auto_bind=auto_bind) as conn:
            conn.search(settings.LDAP_AUTH_SEARCH_BASE,
                        settings.LDAP_AUTH_USER_FILTER.format(**model_fields),
                        attributes=[settings.LDAP_AUTH_USER_ATTRIBUTE])
            if not conn.entries:
                # No user was found
                return settings.LDAP_AUTH_SEARCH_BASE
            if len(conn.entries)>1:
                # More than one user was found
                return settings.LDAP_AUTH_SEARCH_BASE
            # Return the DN of the found user
            return conn.response[0]['dn']
    else:
        return settings.LDAP_AUTH_SEARCH_BASE


```

I also added one new settings the user-filter and changed one to point to the new function:
```python
# from settings.py
# LDAP User Filter.
LDAP_AUTH_USER_FILTER = "(&(objectClass=posixAccount)(uid={username}))"
# Change this to point to new function
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_openldap_filter"
```

Is there an easier way to perform this task or would it be worth to commit the code?

Thanks
Benjamin

**Comment by etianen** [comment]
I don't quite see the point of the new LDAP_AUTH_USER_FILTER. It looks like
you can do everything using your custom LDAP_AUTH_FORMAT_USERNAME function.

Or am I missing something?

**Comment by Rohrdantz** [comment]
The idea was to be able to use a custom filter without requiring to edit the special LDAP_AUTH_FORMAT_USERNAME function for each usecase.

I have seen this field ("user filter) in several authentification modules like in gitea or dokuwiki.

**Comment by etianen** [comment]
From what I can see, you're using "Name Givenname" as the unique identifier
for a user?

In this case, I think the correct thing is to map this to the "username"
field in Django, and have the user log in using that.

Otherwise, you require a two-phase login procedure, where you first look up
a user's first name and last name by username, then bind using those. That
seems really odd, to me.

**Comment by Rohrdantz** [comment]
It really does seem kind of odd. Mapping the username would indeed work, but I find using a full name is quite cumbersome and unituitive in comparison to a username, which is used for all other applications. I wonder if not more people use this feature, since it is also implemented in other software such as [Gitea  Docs](https://docs.gitea.io/en-us/authentication/) : 

> **User Filter (required)**
>    An LDAP filter declaring how to find the user record that is attempting to authenticate. The %s matching parameter will be substituted with login name given on sign-in form.

I digged a little in the source code, which is written in go. They indeed search for the user record first and if exactly one record is found, extract the ldap distinguished name attribute "DN" from it for the bind. This is actually better than what I did in my initial try. I updated the code in the first post accordingly.

**Comment by etianen** [comment]
Okay, that's not so bad.

I think that most of the logic for this belongs in the ``connection`` function, since it can then re-use the same LDAP connection.

https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L121

I'll try to add this in sometime this week for you to review.

**Comment by Rohrdantz** [comment]
That would be really great!

The connection function seems very well suited. Some minor tweaks would be required, since the bind and LDAP connection are currently nested.

I would be more than happy to test.

**Comment by etianen** [comment]
Sorry for the lack of activity on this! Work has been a bit hectic. I will
get onto this eventually.
