### ISSUE TITLE
Don't truncate list-valued attributes

### ISSUE THREAD

**Issue by BenWiederhake** [etianen/django-python3-ldap#135]
I would like to have information about group membership available from the user object.

**Expected**: In a Django view, I can write `'cn=ninja-warrior,ou=groups,dc=example,dc=com' in request.user['memberOf']` to determine whether the logged-in user is a `ninja-warrior`.
**Actual**: Impossible, because [when parsing the LDAP attributes](https://github.com/etianen/django-python3-ldap/blob/82e3a2e/django_python3_ldap/ldap.py#L49), any duplicate "keys" would get pruned.

I'm aware that I need to add `'memberOf: memberOf'` to `LDAP_AUTH_USER_FIELDS`.
Also, I do not have the target LDAP available to me, and I cannot actually run or test anything.  So maybe I'm just reading this wrong.  (Actually I'd be happy to be wrong here.)

I'm very new to Django and LDAP, so maybe my approach is all wrong.

- How do you use django-python3-ldap to check for more nuanced permissions than "user or not"?
- Would you accept a patch that does a more fine-grained resolution of this case?  I imagine it might be helpful to define `memberOf` to be the first element (for backward compatibility) and `memberOf__list` to be the python list of all provided values.  Or something.

Cheers,
Ben

**Comment by etianen** [comment]
I think the correct way to handle this is with django's MultiValueDict.
This can then be passed to settings.LDAP_AUTH_CLEAN_USER_DATA, and treated
as a list if required.

**Comment by BenWiederhake** [comment]
Good idea, that keeps the attribute namespace cleaner and uses more common building blocks.

I implemented it as #137.
