### ISSUE TITLE
Can't figure out how to bind with current LDAP config

### ISSUE THREAD

**Issue by michaelcalve** [etianen/django-python3-ldap#138]
Hello,

Currently the four fields I have to use are url, bindDn, bindCredentials, and searchBase.

How do I map these to the fields displayed in your readme?

currently in ldap3 I am having some success using the following commands

server = Server('url')
conn = Connection(server, 'bindDN', password='bindCredentials')

I am completely new to LDAP and am trying to help my organization out by figuring this out, hopefully for the last time.

When I print the conn after conn.bind()

print(conn)
ldaps://xxx.xxx.xxx.xxx:636 - ssl - user: 'bindDN' - not lazy - bound - open - <local: xxx.xxx.xxx.xxx:54643 - remote: xxx.xxx.xxx.xxx:636> - tls not started - listening - SyncStrategy - internal decoder

**Comment by michaelcalve** [comment]
why is my username coming out like this:

"User: uid=CN\3DLDAP BMD\2COU\3DService Accounts\2Cdc\3Dstring1\2Cstring2\3Dstring2,DC=string1,DC=string2"

**Comment by michaelcalve** [comment]
When I try to login, the username and password that ldap uses are the same as the user credentials I try to login with?

Why is this happening again?

**Comment by spezifanta** [comment]
Yeah had the same problem. This LDAP extension behaves differently than other LDAP tools like Jenkins or GitLab. 
I my case, the sync_user is in a different group than the actual users.
I had to override `LDAP_AUTH_FORMAT_USERNAME`

This is my (working) setup:

```python
...

LDAP_AUTH_SEARCH_BASE = 'ou=users,ou=ldap,dc=example,dc=com'
LDAP_AUTH_CONNECTION_USERNAME = 'foo-service-user'
LDAP_AUTH_CONNECTION_PASSWORD = 'xxx'

def auth_user(model_fields):
    name = model_fields['username']
    if name == LDAP_AUTH_CONNECTION_USERNAME:
      return 'uid={},ou=systemUsers,ou=ldap,dc=example,dc=com'.format(LDAP_AUTH_CONNECTION_USERNAME)
    return  'uid={},ou=users,ou=ldap,dc=example,dc=com'.format(name)

LDAP_AUTH_FORMAT_USERNAME = auth_user
```

**Comment by michaelcalve** [comment]
I think my issue is different still. 

When a user logs in, their username and password are sent to the ldap server in order to connect

**Comment by sonicblind** [comment]
@spezifanta, thanks for your tip. It worked for me, since we also have admin/sync account in different directory than users. It would make sense to have something like LDAP_AUTH_ADMIN_DN available by default in the package.
