### ISSUE TITLE
not woring

### ISSUE THREAD

**Issue by soumyajit40cs** [etianen/django-python3-ldap#139]
I am trying to implement this package for my app, but it's not working. I am using python 3.6 with django 2.1.
This is my setting file. I am unable to understand what is the wrong. Could you please help me.
`# The URL of the LDAP server.
LDAP_AUTH_URL = "ldap://ldap.forumsys.com:389"

# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = False

# The LDAP search base for looking up users.
LDAP_AUTH_SEARCH_BASE = "cn=read-only-admin,dc=example,dc=com"

# The LDAP class that represents a user.
LDAP_AUTH_OBJECT_CLASS = "ou"

# User model fields mapped to the LDAP
# attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "username": "uid",
    #"first_name": "givenName",
    #"last_name": "sn",
    "email": "mail",
}

# A tuple of django model fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
#LDAP_AUTH_CONNECTION_USERNAME = 'username'
LDAP_AUTH_CONNECTION_PASSWORD = 'password'

LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "None"
AUTHENTICATION_BACKENDS = (
'django_python3_ldap.auth.LDAPBackend',
'django.contrib.auth.backends.ModelBackend',
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

`

**Comment by etianen** [comment]
Can you paste the output of your server logs please?

**Comment by soumyajit40cs** [comment]
In console it’s showing ldap connect field. Ldap invalid credentials result 49 invalidcredential none none bindresponse

**Comment by soumyajit40cs** [comment]
Anything wrong in ldap search base and object class

**Comment by etianen** [comment]
It seems to be to do with the ldap bind step. Are you sure you have
configured your settings for OpenLDAP / Active Directory correctly?

**Comment by soumyajit40cs** [comment]
it's openldap. I am using one sandbox ldap setting. This configuration working for my php based drupal application. 
https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

**Comment by soumyajit40cs** [comment]
so what can I do now.
