### ISSUE TITLE
Group sync and concrete group manipulation example

### ISSUE THREAD

**Issue by robindabird** [etianen/django-python3-ldap#141]
Hello,

Is it possible to sync group when launching the command ldap_sync_users ? I would find it very convenient to do it for in-house developed application where the AD is designed around 

Is this possible to add an example where the users of a certain LDAP group are automatically put in staff groups ?

**Comment by robindabird** [comment]
Thanks,

In my settings.py I did the following :
LDAP_AUTH_SYNC_USER_RELATIONS = 'my_project_name.utils.sync_user_relations'

My function utils.sync_user_relations

```
import re
import binascii
from django.utils.encoding import force_text
from django.utils.module_loading import import_string
from django.utils import six
from django.contrib.auth.models import Group, User
from django_python3_ldap.conf import settings
from django_python3_ldap.utils import sync_user_relations

def custom_sync_user_relations(user, ldap_attributes):
        sync_user_relations(user=user, ldap_attributes=ldap_attributes)
        for one_group in ldap_attributes['memberOf']:
                group_search = one_group.split(',')
                group_name =  group_search[0][3:]
                group = Group.objects.get_or_create(name=group_name)
                user.groups.add(Group.objects.get(name=group_name))
                user.save()
```

Thanks for the advice

**Comment by jaarsolares** [comment]
Hi @robindabird 
How do you get the user and the ldap_attributes that you pass to the custom_sync_user_relations function?
I'm trying to get the ldap_attributes['memberOf'] in a Django view but I'm not able to.
Thanks beforehand for the help!

**Comment by robindabird** [comment]
> Hi @robindabird
> How do you get the user and the ldap_attributes that you pass to the custom_sync_user_relations function?
> I'm trying to get the ldap_attributes['memberOf'] in a Django view but I'm not able to.
> Thanks beforehand for the help!

Hello @jaarsolares,

Sorry to answer just now... 

I just edited my previous post, there were several mistakes...
Just add this line in your settings.py:
LDAP_AUTH_SYNC_USER_RELATIONS = 'my_project_name.utils.custom_sync_user_relations'

Of course, be sure to have the function **custom_syn_user_relations** inside **utils**.
And you should be able to have your groups
