### ISSUE TITLE
How to bind correctly in my AD setup

### ISSUE THREAD

**Issue by nova-systems** [etianen/django-python3-ldap#142]
How to bind correctly ? 

If I set the LDAP_AUTH_CONNECTION_USERNAME = none and LDAP_AUTH_COnnection_password = none, My terminal says that connection is Succes but I can;t bind, 

then if I set all with my data I got error as follows, my setup is AD

My settings file :

LDAP_AUTH_URL = "ldap://10.172.90.3:389"
LDAP_AUTH_USE_TLS = False
LDAP_AUTH_SEARCH_BASE = "OU=Users,DC=ad,DC=efektum,DC=pl"
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "ad.efektum.pl"
LDAP_AUTH_OBJECT_CLASS = "user"

LDAP_AUTH_CONNECTION_USERNAME = "adam.dabrowski"
LDAP_AUTH_CONNECTION_PASSWORD = "Das5ahec#23a"

LDAP_AUTH_CONNECT_TIMEOUT = None
LDAP_AUTH_RECEIVE_TIMEOUT = None

LDAP_AUTH_USER_FIELDS = {
    "username": "givenName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

terminal output

LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839 - bindResponse - None

**Comment by etianen** [comment]
Honestly, it could be anything, and the error logs are hardly informative.
I've afraid you'll have to research your own particular LDAP setup.

**Comment by nova-systems** [comment]
how can I debug the problem ?

**Comment by etianen** [comment]
Check that all the settings are correct with whoever runs your LDAP server.
See what effect changing the settings has on the debug messages.

Unfortunately, LDAP error messages are really unhelpful, so it's a tortuous
process.

**Comment by rspeed** [comment]
I believe you need to supply a full DN for the username, since that user may not necessarily be within the search base.

**Comment by ineedme** [comment]
I test your configuration on my office and it worked
in my workplace domain is company.corp
but DAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = companycr

Active Directory User and Computers > Your User Properties > Account > User Logon name (pre-Windows 2000) 
Maybe its not too late
