### ISSUE TITLE
Problem with authentication failure

### ISSUE THREAD

**Issue by leavest** [etianen/django-python3-ldap#145]
A ldap account with a blank attribute of displayName authenticate failed.

error message: LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1 - bindResponse - None

After I set something to displayName, authenticate success.

But in other package like cas can authenticate success when a ldap account has a blank attribute of displayName

**Comment by etianen** [comment]
I have no idea why this would happen. I don't require the display name when
I authenticate.

If you can track this down, I'll take a pull request.

**Comment by leavest** [comment]
I may find the reason.

When I use like ‘domain\\username’ and password to authenticate, it success.

If settings.LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN is not None, 
function django_python3_ldap.ldap.connection need  add a new line.

In line 157, add a new argument authentication='NTLM'.
like:
        c = ldap3.Connection(
            ldap3.Server(
                settings.LDAP_AUTH_URL,
                allowed_referral_hosts=[("*", True)],
            ),
            user=username,
            password=password,
            auto_bind=auto_bind,
            raise_exceptions=True,
            authentication='NTLM'
        )

I will check config for the Microsoft Active Directory later.
Because I am not responsible for the Microsoft Active Directory.

**Comment by leavest** [comment]
It's a bug To connect to a Microsoft Active Directory.
But I'm not sure if that's why I authenticate failed。
