### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by bobort** [etianen/django-python3-ldap#148]
I'm trying to use Pipenv to set up my environment, but there is an issue with this package.
You require version 0.3.2 of pyasn1 (==0.3.2) instead of allowing a more modern version.  I have several other packages that depend on newer versions of pyasn1.  Even your ldap3 dependency allows any version of pyasn1 above 0.1.8.

I appreciate any advice you have to offer.

**Comment by bobort** [comment]
I understand what you're saying.  I managed to work around the issue by just modifying the METADATA file.

I've been using ldap authentication for years using Microsoft Active Directory, and I actually use the django-auth-ldap package which depends on your package.  I constantly have troubles when I am installing any ldap package, and I've used different ones over the years.  It would be nice to have one that just worked out of the box without depending on so many other things.

**Comment by Issen007** [comment]
Hi,
It is more dependencies that need to be updated. It still working with Active Directory (Windows Server 2016) but I think we should just update the dependency list.

ERROR: django-python3-ldap 0.11.2 has requirement ldap3==2.5, but you'll have ldap3 2.5.2 which is incompatible.
ERROR: django-python3-ldap 0.11.2 has requirement pyasn1==0.4.4, but you'll have pyasn1 0.4.5 which is incompatible.

**Comment by etianen** [comment]
I'll happily take a pull request to update dependencies.

Maybe it's time to put in a version range again. Worst case, this means
people have to pin dependencies if pyasn1 or ldap3 break things, but that
at least puts power into the developer's hands.
