### ISSUE TITLE
View security using AD groups

### ISSUE THREAD

**Issue by jaarsolares** [etianen/django-python3-ldap#149]
Is there any way to apply a direct AD group security to limit the access to a view?

**Comment by etianen** [comment]
I'm not really an AD expert! :O

You would probably want to sync the information about group membership to
the user model groups/permissions by overriding the functions in
LDAP_AUTH_CLEAN_USER_DATA and LDAP_AUTH_SYNC_USER_RELATIONS. Then use
normal Django permissions to restrict access to views.

**Comment by schottz** [comment]
@etianen First of all, thanks for your support.

In this case, doesn't it support checking the group at logon?

**Comment by etianen** [comment]
If the user is missing a required group in LDAP, you can set the is_active
flag of the user model to False in LDAP_AUTH_CLEAN_USER_DATA or
LDAP_AUTH_SYNC_USER_RELATIONS.

**Comment by schottz** [comment]
But, in this case, only users that match the required group would be able to access the page. Right?

**Comment by etianen** [comment]
You can either sync the LDAP groups to the User model, and then on
protected pages check that the logged-in user has the correct groups,

OR

Mark the user as is_active = False, if the user doesn't have a required
LDAP group, in order to forbid access to the whole site.

**Comment by schottz** [comment]
Thank you again :)

*Felipe Schottz*

**Comment by schottz** [comment]
I'm sorry bother you again, but how can I sync LDAP groups? I've tried `python .\manage.py ldap_sync_users`, but couldn't find anything related to my ldap groups on django admin.

**Comment by etianen** [comment]
The setting LDAP_AUTH_SYNC_USER_RELATIONS allows you to customize syncing ldap data to the user model.

```
# Path to a callable that takes a user model and a dict of {ldap_field_name: [value]},
# and saves any additional user relationships based on the LDAP data.
# Use this to customize how data loaded from LDAP is saved to User model relations.
# For customizing non-related User model fields, use LDAP_AUTH_CLEAN_USER_DATA.
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
```

It's up to you to introspect the LDAP data dict, and customer the user model.
