### ISSUE TITLE
Don't create User after succesfull login

### ISSUE THREAD

**Issue by akkerd** [etianen/django-python3-ldap#152]
I am new to Django. I have succesfully made the loggin with my LDAP server, but I don't need to create a User in my DB after a successful login, as I want to manage them manually. I am suspecting that I need to use LDAP_AUTH_CLEAN_USER_DATA and LDAP_AUTH_SYNC_USER_RELATIONS for achieving my purpose, but I am missing a clear example of how to use this objects.

Can anyone help me here? Do I need to delete the user everytime after a login or can I set it up so it does not create any user? 

This is my sttings.py:
```
############## LDAP ##############

# The URL of the LDAP server.
LDAP_AUTH_URL = 'ldap://some.top.address:389'
AUTHENTICATION_BACKENDS = [
    'django_python3_ldap.auth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = False

# The LDAP class that represents a user.
LDAP_AUTH_OBJECT_CLASS = "user"

LDAP_AUTH_USER_FIELDS = {}
# A tuple of fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

# Use this to customize how data loaded from LDAP is saved to the User model.
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
# For customizing non-related User model fields, use LDAP_AUTH_CLEAN_USER_DATA.
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
# Returns a list of [ldap_search_filter]. The search filters will then be AND'd together when creating the final search filter.
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

# Use this to support different types of LDAP server.
# LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_openldap"
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

# Sets the login domain for Active Directory users.
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "someDirectory"


# The LDAP username and password of a user for querying the LDAP database for user
# details. If None, then the authenticated user will be used for querying, and
# the `ldap_sync_users` command will perform an anonymous query.
LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_PASSWORD = None

# Set connection/receive timeouts (in seconds) on the underlying `ldap3` library.
# LDAP_AUTH_CONNECT_TIMEOUT = 1000
# LDAP_AUTH_RECEIVE_TIMEOUT = 1000

# The LDAP search base for looking up users.
# LDAP_AUTH_SEARCH_BASE = "dc=some,dc=top,dc=address"
LDAP_AUTH_SEARCH_BASE = 'ou=Users,ou=SA,ou=SomeAddress,dc=some,dc=top,dc=adress'

# User model fields mapped to the LDAP
# attributes that represent them.


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
```

Thanks in advance.

**Comment by etianen** [comment]
For Django to work, there needs to be some sort of record in the user
database representing a user login. django-python3-ldap uses the LDAP
server as the source of truth about user accounts, and expects you to
update the user details in LDAP, not the Django database.

**Comment by AkkerD** [comment]
Okay, I see. What I want is exactly what you describe, use LDAP server as a source of truth, but keep my Django database separated.

I have some UserIDs in the Django database and that correlates with the ID in the LDAP server. What I need is to decline the authentication if the UserID is not in Django, even though it might exist in the LDAP server. In that case I want to inform the user that he is not whitelisted in our system.

Is there a way to do that with your library @etianen ?

Thanks again for your help.

**Comment by etianen** [comment]
You should add some attribute to the user's LDAP record to mark them as not
whitelisted for the site. Then, in LDAP_AUTH_CLEAN_USER_DATA, set is_active
to false if the user is not whitelisted.

That way, the LDAP database stays the single source of truth, including the
whitelisting information.
