### ISSUE TITLE
Retrieve multiple values for attribute is not possible

### ISSUE THREAD

**Issue by Drau** [etianen/django-python3-ldap#153]
Hi, 
When authenticating against the LDAP its possible to provide  

LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "groups": "memberOf",
    "email": "mail",
}

My problem is that my LDAP account contains multiple "memberOf" attributes, and i need to get them all. 
Unfortunately when printing the dict received in  LDAP_AUTH_CLEAN_USER_DATA custom method i specified, I only get 1 value of "memberOf" in the "groups" key.

Is it possible to somehow retrieve all keys?  Im guessing LDAP has a multi value API for such occasions.. 

Thanks ! :)

**Comment by etianen** [comment]
It's not supported by the library at the moment, unfortunately. It would be
pretty easy to use a django MultiValueDict here:

https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L47

Which would allow current code to keep working while providing access to
multiple LDAP values when desired.

I'd take a pull request for that feature.
