### ISSUE TITLE
LDAP connect failed: LDAPInvalidCredentialsResult

### ISSUE THREAD

**Issue by cconnerj** [etianen/django-python3-ldap#156]
I am unable to authenticate using django-python3-ldap, I am able to ldapsearch with the same credentials and run `python3.6 manage.py ldap_sync_users` and able to import all user info, but cannot login with any of the users on my webapp (doesn't recognize passwords it looks like)

Error:

     LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839 - bindResponse - None
        WARNING:django_python3_ldap.ldap:LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839 - bindResponse - None
        xt error, data 52e, v3839 - bindResponse - None

    
Settings.py

    AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
        'django_python3_ldap.auth.LDAPBackend',
    ]
    
    LOGIN_URL = '/'
    LOGOUT_REDIRECT_URL = '/logout'
    LDAP_AUTH_OBJECT_CLASS = "user"
    
    LDAP_AUTH_URL = "ldap.server.com"
    
    LDAP_AUTH_SEARCH_BASE = 'OU=Engineering,OU=group1,OU=group2,DC=company,DC=com'
    LDAP_AUTH_USER_FIELDS = {
        "mail": "mail",
        "name": "cn",
        "username": "userPrincipalName"}
    
    LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
    
    LDAP_AUTH_USE_TLS = True
    
    LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
    
    LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
    
    LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"
    
    LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"
    
    LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "company.com"
    
    LDAP_AUTH_CONNECTION_USERNAME = "<username>"
    
    LDAP_AUTH_CONNECTION_PASSWORD = "<password>"
    
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
        },
        "loggers": {
            "django_python3_ldap": {
                "handlers": ["console"],
                "level": "INFO",
            },
        },
    }

What am i doing incorrectly in the configuration?

**Comment by cconnerj** [comment]
When users login they use userPrincipalName as their username, but when connecting to the ldap server it would look something like this `CN = John Smith, OU=Engineering,OU=group1,OU=group2,DC=company,DC=com` should i be changing `
LDAP_AUTH_USER_LOOKUP_FIELDS` to 'first_name` instead of `username`... because when i do that it gives me no errors but still unable to login

**Comment by cconnerj** [comment]
It would help to know what exactly the search looks like when it goes to authenticate to the ldap server, so if i login as john.smith@company.org what is sent the ldap server with the above config i have? is it authenticating like so `CN = John Smith, OU=Engineering,OU=group1,OU=group2,DC=company,DC=com` ? or is it using the `userPrincipalName`?

**Comment by etianen** [comment]
`LDAP_AUTH_USER_FIELDS` maps fields on the `User` model to fields on your LDAP record.
`LDAP_AUTH_USER_LOOKUP_FIELDS` specifies the Django model fields that uniquely identify your user both as a Django model **and** an LDAP record.

With your configuration, you are saying:
- `User.username` uniquely identifies a user model
- `userPrincipalName` corresponds to `User.username` in your LDAP record
- `userPrincipalName` uniquely identifies a user within `LDAP_AUTH_SEARCH_BASE`.

If a user types in username: "admin", password: "password" at the django login prompt, django-python3-ldap will:

1. Attempt to bind to the ldap server using `userPrincipalName=admin, OU=Engineering,OU=group1,OU=group2,DC=company,DC=com`
2. If successful, rebind using `LDAP_AUTH_CONNECTION_USERNAME` and `LDAP_AUTH_CONNECTION_PASSWORD`
3. If successful, get_or_create a `User` model using `username="admin"
