### ISSUE TITLE
Authenticating existing users only

### ISSUE THREAD

**Issue by stinovlas** [etianen/django-python3-ldap#157]
I have a question to which I didn't find the answer in the README:

Is there a way to only use `django-python3-ldap` for authenticating users that already exist in a database? Failing authentication if they don't exist?

Could I use something like this?
```python
LDAP_AUTH_CLEAN_USER_DATA = (lambda x: raise Exception)
```

**Comment by etianen** [comment]
That's not really how the library's intended to be used. The idea is that
the LDAP directory is the source of truth.

You shoud add an attribute to LDAP users who you want to be able to log in,
and set is_enabled to False in LDAP_AUTH_CLEAN_USER_DATA if that attribute
is not present.

**Comment by stinovlas** [comment]
I was worried you might say that. Thanks anyway!
