### ISSUE TITLE
Is it possible to add users to LDAP with this library automatically?

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [etianen/django-python3-ldap#158]
Is it possible to add users to LDAP with this library automatically?
I'm trying to do:

`        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            #login(request, user)`

but I always get error in the authentication. I guess it's because this library does not allow user creation.

How could I add users to LDAP quickly with django?

**Comment by etianen** [comment]
You'll have to do this yourself using the ldap3 library.
django-python3-ldap only supports reading users from LDAP.
