### ISSUE TITLE
ldap_promote should be case-insensitive

### ISSUE THREAD

**Issue by NoFr1ends** [etianen/django-python3-ldap#160]
The command ldap_promote should ignore cases in the username

**Comment by etianen** [comment]
I don't think so. The Django treats usernames as case-sensitive, so I think
django-python3-ldap has to as well.

**Comment by NoFr1ends** [comment]
Then the ldap login should force this too, because I know some cases where people tried to promote someone and always got the message that the user doesn't exists.
Maybe we should just implement a message that another user was found with the username which does not match the cases?

**Comment by etianen** [comment]
I think every aspect of user management in Django is case sensitive though.
Login is. ./manage.py changepassword is. Why should ldap_promote be the
exception?
