### ISSUE TITLE
Could not connect to LDAP server

### ISSUE THREAD

**Issue by detininroman** [etianen/django-python3-ldap#161]
Nice to see you helping people stuck with your lib. Unfortunately, I'm one of them:( I've read many issues and some of them describe difficulties seems like my ones. However, I still did not find the solution. 
I cannot authenticate in Active Directory. Error message is following:
 `LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580 - bindResponse - None`

Also, when I run `./manage.py ldap_sync_users`, I could not connect to LDAP server.
Below is my `settings.py`

```python

AUTHENTICATION_BACKENDS = [
    'django_python3_ldap.auth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]
# The URL of the LDAP server.
LDAP_AUTH_URL = "ldap://server.com"

# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = False

# The LDAP search base for looking up users.
LDAP_AUTH_SEARCH_BASE = "OU=someOU,DC=someDC,DC=someDC,DC=someDC"

# The LDAP class that represents a user.
LDAP_AUTH_OBJECT_CLASS = "user"

# User model fields mapped to the LDAP
# attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# A tuple of django model fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

# Path to a callable that takes a dict of {model_field_name: value},
# returning a dict of clean model data.
# Use this to customize how data loaded from LDAP is saved to the User model.
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

# Path to a callable that takes a user model and a dict of {ldap_field_name: [value]},
# and saves any additional user relationships based on the LDAP data.
# Use this to customize how data loaded from LDAP is saved to User model relations.
# For customizing non-related User model fields, use LDAP_AUTH_CLEAN_USER_DATA.
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

# Path to a callable that takes a dict of {ldap_field_name: value},
# returning a list of [ldap_search_filter]. The search filters will then be AND'd
# together when creating the final search filter.
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

# Path to a callable that takes a dict of {model_field_name: value}, and returns
# a string of the username to bind to the LDAP server.
# Use this to support different types of LDAP server.
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"

# Sets the login domain for Active Directory users.
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "domain.com"

# The LDAP username and password of a user for querying the LDAP database for user
# details. If None, then the authenticated user will be used for querying, and
# the `ldap_sync_users` command will perform an anonymous query.
LDAP_AUTH_CONNECTION_USERNAME = 'name.surname@domain.com'
LDAP_AUTH_CONNECTION_PASSWORD = 'password'

# Set connection/receive timeouts (in seconds) on the underlying `ldap3` library.
LDAP_AUTH_CONNECT_TIMEOUT = None
LDAP_AUTH_RECEIVE_TIMEOUT = None


INSTALLED_APPS = [
    ...
    'django_python3_ldap',
]
```
By the way, is that correct to log in like written [here](https://docs.djangoproject.com/en/2.2/topics/auth/default/#topic-authorization), even if I use your backend?
![Screenshot 2019-07-05 at 17 59 57](https://user-images.githubusercontent.com/25865133/60730943-f3ea6100-9f4e-11e9-8208-2c7a388de2df.png)

**Comment by detininroman** [comment]
By the way, is that correct to log in like written here, even if I use your backend?
[Link](https://docs.djangoproject.com/en/2.2/topics/auth/default/#topic-authorization)
![Screenshot 2019-07-05 at 17 59 57](https://user-images.githubusercontent.com/25865133/60730943-f3ea6100-9f4e-11e9-8208-2c7a388de2df.png)

**Comment by etianen** [comment]
Yes. The ldap auth backend in this package should work with the Django auth
views.

**Comment by sonicblind** [comment]
"data 52e" in LDAP error message means invalid credentials:
https://www-01.ibm.com/support/docview.wss?uid=swg21290631

It depends on what you are trying to do.
If you are trying to authenticate a user in my_view, this library takes the provided credentials and use them to bind with your LDAP. In this case, the credentials or the DN or something else in your LDAP config is not right.

If you are running ldap_sync_users, then the library takes credentials configured in LDAP_AUTH_CONNECTION_USERNAME and LDAP_AUTH_CONNECTION_PASSWORD and tries to bind with them. This account is supposed to have privileges to perform LDAP queries.

I suggest you to use utility such as ldapsearch directly from your server's command line, to make sure you are able to talk to LDAP before trying to talk to LDAP via Django.

**Comment by detininroman** [comment]
Thanks, I've solved my problem.
