### ISSUE TITLE
How to add relationship to self on User Model

### ISSUE THREAD

**Issue by DanSantoDomingo** [etianen/django-python3-ldap#162]
I extended the user model to add the manager field.

```
class User(AbstractUser):
    display_name = models.CharField(max_length=500, blank=True)
    title = models.CharField(max_length=255, blank=True)
    company = models.CharField(max_length=255, blank=True)
    manager = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.display_name
```

But im getting this error
`ValueError: Cannot assign "'CN=Dy\\, Name,OU=Users,OU=Accounts,OU=***,OU=AP,OU=***,DC=***,DC=***'": "User.manager" must be a "User" instance.`

**Comment by sonicblind** [comment]
Looks like you are trying to assign a DN value to User.manager instead of a User instance.
You should do something like:

```
john = User.objects.create(display_name='John', title='Foo', company='Bar')
mark = User.objects.create(display_name='Mark', title='Foo', company='Bar', manager=john)
```

**Comment by DanSantoDomingo** [comment]
@sonicblind I want it to be created when i run ldap_sync_users

**Comment by etianen** [comment]
Check out LDAP_AUTH_SYNC_USER_RELATIONS

https://github.com/etianen/django-python3-ldap

**Comment by DanSantoDomingo** [comment]
Sorry im a noob, no idea what to do :(

**Comment by sonicblind** [comment]
ldap_sync_users eventually calls 
`django_python3_ldap.ldap.Connection.iter_users()`

It loops through all LDAP users and return them as User objects:

`django_python3_ldap.ldap.Connection._get_or_create_user()`

This method, before returning the User object calls mentioned LDAP_AUTH_SYNC_USER_RELATIONS.
By default, this is mapped to django_python3_ldap.utils.sync_user_relations as defined in LDAP config: 
`LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"`

`sync_user_relations` does nothing by default. You need to override it.
It allows you to define your own actions after a User object has been created or updated.

However, I think that what you want to do is a bit tricky, as you need to make sure that a "manager" User object exists in your DB before you assign this manager's User object to new user's User object.
And the `sync_user_relations` runs through LDAP in no such guaranteed order which would ensure that someones manager is always fetched before this user.

I would override the existing `class Command(BaseCommand)` in `django_python3_ldap.management.commands.ldap_sync_users` and only update the manager field once all users are in DB.
