### ISSUE TITLE
Does it support rest-framework?

### ISSUE THREAD

**Issue by gekmcfh** [etianen/django-python3-ldap#163]
Is it possible to provide a set of REST API endpoints for authentication using django-python3-ldap as authentication backend to api by djangorestframework now?

**Comment by sonicblind** [comment]
This could help you get an idea how to create your own API endpoint for login using any authentication backend. Django will use django_python3_ldap as soon as you include it in AUTHENTICATION_BACKENDS.


settings.py:
- add rest_framework and django_python3_ldap to INSTALLED_APPS
- add django_python3_ldap.auth.LDAPBackend to AUTHENTICATION_BACKENDS

urls.,py:
- add path('login/', APILogin.as_view(), name='login') to urlpatterns

views.py:

```
class APILogin(APIView):
    permission_classes = (AllowAny,)
    authentication_classes = (
        SessionAuthentication,
        ExemptCsrfFromSessionAuth,
    )

    def post(self, request):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return Response(LoginUserSerializer(user).data)
```


utils.py:
```
class ExemptCsrfFromSessionAuth(SessionAuthentication):
    def enforce_csrf(self, request):
        return
```

serializers.py:
```
from django.contrib.auth import authenticate

class LoginSerializer(serializers.Serializer):
    username = serializers.CharField()
    password = serializers.CharField()

    def validate(self, attrs):
        user = authenticate(
            username=attrs['username'],
            password=attrs['password']
        )
        if not user or not user.is_active:
            raise exceptions.AuthenticationFailed('Login failed')

        return {'user': user}
```

**Comment by gekmcfh** [comment]
Thank you for help!
But i use all of that stack django+rest_api at first time, could you please explain (or add includes) whether `login(request, user)` imported from from django.contrib.auth and i cannot understand where did you get from Response and Login**User**Serializer ?

**Comment by sonicblind** [comment]
```
from django.contrib.auth import login, logout
from rest_framework.response import Response
```

Normally you would return something like this from the APILogin:
`return Response(serializer.validated_data)`

But I didn't want to return all data for a user, so I used second very simple serializer for that, although there might be smarter options out there. I also use the rest framework the first time :)

```
from django.contrib.auth import get_user_model
class LoginUserSerializer(serializers.ModelSerializer):
    class Meta:
        model = get_user_model()
        fields = ('username', 'last_login')
```

**Comment by esavci-luckyeye** [comment]
i know this is old but i wanted to ask @sonicblind that it still asks me a csrf token when i try to send a request after FIRST login. how can i resolve that? i actually want to use token authentication with ldap and rest api.
