### ISSUE TITLE
Unable to log into admin page with AD account and accounts are not getting stored

### ISSUE THREAD

**Issue by jcanning** [etianen/django-python3-ldap#164]
Hey all,

I am trying to set this up but I either do not understand how this is supposed to work or I am missing something totally silly.

I have the following set up
`
AUTHENTICATION_BACKEND = [
    'django_python3_ldap.auth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

#### LDAP Config ####

# The URL of the LDAP server.
LDAP_AUTH_URL = 'ldap://server.domain.com:389'

# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = False

# The LDAP search base for looking up users.
LDAP_AUTH_SEARCH_BASE = "ou=employees,dc=domain,dc=com"

# User model fields mapped to the LDAP attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# Username
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "DOMAIN"
LDAP_AUTH_CONNECTION_USERNAME = 'username'
LDAP_AUTH_CONNECTION_PASSWORD = 'password'

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}
`
I do not get any errors at all but it does not even seem to try to connect to the ldap server

![image](https://user-images.githubusercontent.com/4312814/62074957-45b69c00-b21a-11e9-94cf-8650270635f9.png)

If i run the ./manage ldap_sync_users, it does sync them to my users database but i am unable to login with the synced user.

`LDAP user lookup succeeded
Synced FNameLName`

If i try to do promote a user it lets me but still cannot log in with them.

What am i doing wrong here? 

Thanks in advance.

**Comment by etianen** [comment]
I think you're going to have to step through the django-python3-ldap code with `print()` statements until you can figure out what is going wrong. There should be a logging message if authentication fails. If you're not getting a logging message, either your logging setup is screwed, or you've found a bug in django-python3-ldap
