### ISSUE TITLE
Possibility to see nested groups

### ISSUE THREAD

**Issue by AGlowczewska** [etianen/django-python3-ldap#165]
While we create function connected with LDAP_AUTH_SYNC_USER_RELATIONS, the variable **ldap_attributes** is provided by the library. It would be reaaaly helpful if it provided also nested groups - right now it provides the ones for which the user is a direct member.

As for anybody who have the same problem, the workaround I found was to create a new ldap query: '(&(member:1.2.840.113556.1.4.1941:=' + distinguished_name + ')(objectClass=group))' and execute it.

**Comment by etianen** [comment]
I think you'll have to do it with a nested query. Not everyone needs nested
groups, and querying for them is an additional overhead and complexity.
