### ISSUE TITLE
Django Model field is Integer(FK) and Active Directory attribute for corresponding field is String. Can I make it work?

### ISSUE THREAD

**Issue by selimatmaca** [etianen/django-python3-ldap#169]
Hi all,
 
In my environment, django-python3-ldap works just perfect with Active Directory. Users can log in, database creates the new users on the fly and I can manually sync all users from Active Directory to my User Model, if I need to. Thanks a lot for this great library.

The issue is, I  have some custom field in my User Model (department_id, subdivision_id) and they are FKs, so I had to create integer fields on Active Directory. When we create a new user on the AD, we need to remember the correct integer values for the departments and subdivisions. 

So, It will be easier for us to just type the department and subdivision names as string such as IT, HR and so on as department. However, I dont know how I can convert this string value to corresponding integer value for the department in User Model. Can I use a python dictionary in my settings.py or something like that or any advice you you might give?

LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
    "role": "title",
    "department_id": "departmentId",
    "subdivision_id": "subdivisionId",
}

**Comment by etianen** [comment]
Look into the LDAP_AUTH_CLEAN_USER_DATA and LDAP_AUTH_SYNC_USER_RELATIONS
settings, which are paths to callables that let you fiddle with the
incoming LDAP data before sending it on to be saved to the user model.

**Comment by selimatmaca** [comment]
Thanks etianen.
