### ISSUE TITLE
cannot import name 'six' from 'django.utils' after upgrading to Django 3

### ISSUE THREAD

**Issue by Mansikka** [etianen/django-python3-ldap#173]
Hi

Django 3.0 was just released, so I decided to upgrade our exisiting django project to it. Naturally, something broke (as it always does on big number change).

In this case, we have been using django-python3-ldap to sync our users (because every other ldap solution just flat out failed). So in our test, we cleared out everything, did the upgrade and tried to sync users. Follow error was provided:

ImportError: cannot import name 'six' from 'django.utils' (C:\Users\Mansikka\AppData\Local\Continuum\miniconda3\envs\djEnv\lib\site-packages\django\utils\__init__.py)

**Comment by etianen** [comment]
v0.11.3, released yesterday, makes no mention of django.utils.six, and has been tested against Django 3.0.

I'd check which version of django-python3-ldap you're using.

**Comment by Mansikka** [comment]
You were right. We were running 0.11.2. Update fixed the issue.
