### ISSUE TITLE
Is there a way to authenticate - but not sync the users data?

### ISSUE THREAD

**Issue by hannylicious** [etianen/django-python3-ldap#177]
We use this library but have a specific use case where we _just_ need to authenticate a user with LDAP to log them in - but that's it. We don't need to sync their data to the django Users model.

Is there a setting to allow for that with this library?

**Comment by hannylicious** [comment]
Nevermind - I apologize. I wasn't thinking through this very well.

I see that you can use `LDAP_AUTH_USER_FIELDS` to specify which fields are sync'd... you can just remove fields from there and those fields will not sync automatically - which is exactly what I was looking to do!

**Comment by etianen** [comment]
A mini adventure! :P

Glad you figured it out.
