### ISSUE TITLE
LDAP bind failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None

### ISSUE THREAD

**Issue by madsholme** [etianen/django-python3-ldap#178]
Hi

If i try and login with a domain user, i get this error:
`LDAP bind failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None`

now if i try and login with the user i am using in the settings.py to do the ldap auth, i get

`LDAP connect succeeded
LDAP user lookup failed`

that seems correct as the service accoutn is not in the same place as the domain users. Also if i run the ldap_sync_users i can see its pulling users from the correct ou. But i dont want all my users sync to the db, so i see no reason to do the sync, as the user is supposed to be synced when they login right?

`
LDAP_AUTH_URL = "ldap://dc01.intern.domain.local:389"

LDAP_AUTH_USE_TLS = False

LDAP_AUTH_SEARCH_BASE = "OU=MyUsers,DC=intern,DC=domain,DC=local"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

LDAP_AUTH_CONNECTION_USERNAME = 'XXXX'
LDAP_AUTH_CONNECTION_PASSWORD = 'Xyx'

LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

LDAP_AUTH_OBJECT_CLASS = "user"`

any idea what i am missing? (im testing the login on the admin login page)

**Comment by hannylicious** [comment]
I'm also curious on this - as I recently noticed this WARNING posting in our error logs in Apache recently. Our LDAP setup is slightly different, and ultimately it checks the users logging in, but I'm curious about the resolution of this because maybe it will help me as well.

**Comment by madsholme** [comment]
```
# The URL of the LDAP server.
LDAP_AUTH_URL = "ldap://dc01.intern.domain.local:389"

# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = True

# The LDAP search base for looking up users.

LDAP_AUTH_SEARCH_BASE = "OU=MyUsers,DC=intern,DC=domain,DC=local"                
# The LDAP class that represents a user.

LDAP_AUTH_OBJECT_CLASS = "organizationalPerson"

# User model fields mapped to the LDAP
# attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "username": "userPrincipalName",
    #"username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",

}

# A tuple of django model fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

# Path to a callable that takes a dict of {model_field_name: value},
# returning a dict of clean model data.
# Use this to customize how data loaded from LDAP is saved to the User model.
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

# Path to a callable that takes a user model and a dict of {ldap_field_name: [value]},
# and saves any additional user relationships based on the LDAP data.
# Use this to customize how data loaded from LDAP is saved to User model relations.
# For customizing non-related User model fields, use LDAP_AUTH_CLEAN_USER_DATA.
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

# Path to a callable that takes a dict of {ldap_field_name: value},
# returning a list of [ldap_search_filter]. The search filters will then be AND'd
# together when creating the final search filter.
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

# Path to a callable that takes a dict of {model_field_name: value}, and returns
# a string of the username to bind to the LDAP server.
# Use this to support different types of LDAP server.
#LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_openldap"
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
# Sets the login domain for Active Directory users.
#LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = None

# The LDAP username and password of a user for authenticating the `ldap_sync_users`
# management command. Set to None if you allow anonymous queries.
LDAP_AUTH_CONNECTION_USERNAME = 'YYYYYYYY'
LDAP_AUTH_CONNECTION_PASSWORD = 'XXXXXXX'
```

This seems to work if i login as username@email.com
but if i change it to

```
LDAP_AUTH_USER_FIELDS = {  
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",

}

```

it does not work with my username only. What am i missing?

**Comment by rorynscott** [comment]
@madsholme were you ever able to figure this out? We're running into the same issue; works fine with email, but sAMAccountName fails with the error you posted above.

**Comment by madsholme** [comment]
@rorynscott  no sorry ... i kinda gave up :(

**Comment by soekarmana** [comment]
@rorynscott @madsholme 
try to debug it with option` LDAP_AUTH_USE_TLS = False`, then capture ldap server responses with wireshark
in my case, the server does not accept "server.com\user.name" format, but accept "user.name@server.com"
according to docs, it is  user-principal-name format

change the settings to :
```
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "domain.com"
```
for me, this solves the problem

**Comment by JonnyB1438** [comment]
I have the same problem and I have debugged this functionality. ldap3 always authorizes using the "displayName" field and this is not configurable. If the values of your LDAP_AUTH_USER_FIELDS["username"] fields are not equal to the values of the "displayName" fields, you will have errors. I didn't find how to fix it, but "displayName" is a bad choice for authorization.

**Comment by madsholme** [comment]
In my setup username and display name are not the same, and i can auth just fine with username. this is my setup:

`

# The URL of the LDAP server.
LDAP_AUTH_URL = "ldap://domaincontroller.internal.domain.com:389"

# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = False

# The LDAP search base for looking up users.

LDAP_AUTH_SEARCH_BASE = "OU=Users,DC=internal,DC=domain,DC=com"                        
# The LDAP class that represents a user.
LDAP_AUTH_OBJECT_CLASS = "organizationalPerson"

# User model fields mapped to the LDAP
# attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",

}

# A tuple of django model fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

# Path to a callable that takes a dict of {model_field_name: value},
# returning a dict of clean model data.
# Use this to customize how data loaded from LDAP is saved to the User model.
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

# Path to a callable that takes a user model and a dict of {ldap_field_name: [value]},
# and saves any additional user relationships based on the LDAP data.
# Use this to customize how data loaded from LDAP is saved to User model relations.
# For customizing non-related User model fields, use LDAP_AUTH_CLEAN_USER_DATA.
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

# Path to a callable that takes a dict of {ldap_field_name: value},
# returning a list of [ldap_search_filter]. The search filters will then be AND'd
# together when creating the final search filter.

LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"


# Path to a callable that takes a dict of {model_field_name: value}, and returns
# a string of the username to bind to the LDAP server.
# Use this to support different types of LDAP server.

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"
# Sets the login domain for Active Directory users.
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = 'internal.domain.com'

# The LDAP username and password of a user for authenticating the `ldap_sync_users`
# management command. Set to None if you allow anonymous queries.
LDAP_AUTH_CONNECTION_USERNAME = 'User'
LDAP_AUTH_CONNECTION_PASSWORD = 'MyPW`

**Comment by JonnyB1438** [comment]
This helped, thanks.
