### ISSUE TITLE
is possible?

### ISSUE THREAD

**Issue by daltonpinheiro** [etianen/django-python3-ldap#180]
hi,
The Admin of my company said which to connect Active Directory  you only need this parameters.
url: 'ldap://dc.domain.com',
               baseDN: 'dc=domain,dc=com',
               username: 'username@domain.com',
               password: 'password'
How do i config putting only 4 elements?
Because other languages you only need this parameters (Ex nodejs).
With this settings i can to execute ldap sync users and put all users of my company in table auth_user, but i can't entrance in django admin with this users.
My settings is:
LDAP_AUTH_URL = 'ldap://xxx.xxx.xxx.xxx:389'
LDAP_AUTH_USE_TLS = False
LDAP_AUTH_SEARCH_BASE = "OU=Usuarios,OU=HOSPITAL,DC=hospitalnet,DC=hospital,DC=gov,DC=br"
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}
LDAP_AUTH_OBJECT_CLASS = "user"
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "hospital.gov.br"
LDAP_AUTH_CONNECTION_USERNAME = 'authenticate@hospitalnet.hospital.gov.br'
LDAP_AUTH_CONNECTION_PASSWORD = 'password'
LDAP_AUTH_CONNECT_TIMEOUT = None
LDAP_AUTH_RECEIVE_TIMEOUT = None
AUTHENTICATION_BACKENDS = (
    "django_python3_ldap.auth.LDAPBackend",
    'django.contrib.auth.backends.ModelBackend'
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

Thanks

**Comment by etianen** [comment]
What log output do you get when you try to login?

**Comment by daltonpinheiro** [comment]
Thanks for answer my question faster .
I'm working in hospital and i need to deploy any applications for help doctors and nurses to treat pacients with the Covid19.
My output when i try login in django admin is:
LDAP bind failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C090421, comment: AcceptSecurityContext error, data 52e, v23f0 - bindResponse - None
[28/Apr/2020 15:25:42] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1986

**Comment by etianen** [comment]
Hmm, that's not a helpful message.

It might be worth sprinkling a few print statements around the
django_python3_ldap/ldap.py codebase to figure out where in particular the
error is occurring.

Given that you're working for something pretty worthwhile, I'd be happy to
debug this personally, but you'd need to give me the real access
credentials for your LDAP server, and access to the LDAP server itself. I
realise, however, that data protection will probably make this impossible.

**Comment by daltonpinheiro** [comment]
Thanks Dave Hall,
I inserted some print in ldap.py, and i dicovered which insert a print(c.bind()) and comment other part of code, its worked.
I don't know because
Follow this code:
@contextmanager
def connection(**kwargs):
    """
    Creates and returns a connection to the LDAP server.

    The user identifier, if given, should be keyword arguments matching the fields
    in settings.LDAP_AUTH_USER_LOOKUP_FIELDS, plus a `password` argument.
    """
    # Format the DN for the username.
    format_username = import_func(settings.LDAP_AUTH_FORMAT_USERNAME)
    kwargs = {
        key: value
        for key, value
        in kwargs.items()
        if value
    }
    username = None
    password = None
    if kwargs:
        password = kwargs.pop("password")
        username = format_username(kwargs)
    # Connect.
    try:
        #print("###here2#### %s"%username)
        c = ldap3.Connection(
            ldap3.Server(
                settings.LDAP_AUTH_URL,
                allowed_referral_hosts=[("*", True)],
                get_info=ldap3.NONE,
                connect_timeout=settings.LDAP_AUTH_CONNECT_TIMEOUT,
            ),
            user=username,
            password=password,
            auto_bind=False,
            raise_exceptions=True,
            receive_timeout=settings.LDAP_AUTH_RECEIVE_TIMEOUT,
        )
        print(c.bind())#I don't know because this is needed.
        #print(" settings.LDAP_AUTH_CONNECTION_USERNAME = %s"%settings.LDAP_AUTH_CONNECTION_USERNAME)
    except LDAPException as ex:
        logger.warning("LDAP connect failed: {ex}".format(ex=ex))
        yield None
        return
    # Configure.
    yield Connection(c)
    c.unbind()
    
    '''
    try:        
        # Start TLS, if requested.
        if settings.LDAP_AUTH_USE_TLS:
            c.start_tls(read_server_info=False)
        # Perform initial authentication bind.
        c.bind(read_server_info=True)
        # If the settings specify an alternative username and password for querying, rebind as that.
        if (
            (settings.LDAP_AUTH_CONNECTION_USERNAME or settings.LDAP_AUTH_CONNECTION_PASSWORD) and
            (
                settings.LDAP_AUTH_CONNECTION_USERNAME != username or
                settings.LDAP_AUTH_CONNECTION_PASSWORD != password
            )
        ):
            User = get_user_model()
            print("linha180  %s"% username)
            c.rebind(
                user=format_username({User.USERNAME_FIELD: settings.LDAP_AUTH_CONNECTION_USERNAME}),
                password=settings.LDAP_AUTH_CONNECTION_PASSWORD,
            )
        # Return the connection.
        logger.info("LDAP connect succeeded")
        yield Connection(c)
    except LDAPException as ex:
        print("###aqui####",cf.f_lineno )
        logger.warning("LDAP bind failed: {ex}".format(ex=ex))
        yield None
    finally:
        c.unbind()
    '''

**Comment by etianen** [comment]
And if you remove the print statements it stops working?! That sounds...
odd.

**Comment by daltonpinheiro** [comment]
In fact, it's just the statement "print (c.bind ())" inside this "def connection" above.

**Comment by etianen** [comment]
That is... insane. I've just checked the source code of the ldap3 library
that underpins django-python3-ldap. The bind() function returns a boolean
value. There's no way that printing out a boolean value should affect the
operation of the authentication.

I don't really know what to suggest.

Does a print("foo") statement above and below the problematic line also fix
the problem?

**Comment by daltonpinheiro** [comment]
When I use  print("foo"), this message appears when I login.
Same message without print(c.bind()).


LDAPSocketOpenError at /admin/login/
unable to send message, socket is not open
Request Method:	POST

**Comment by daltonpinheiro** [comment]
I'm sorry, I was making a mistake in the settings.
The configuration of ldap in my company uses LDAP_AUTH_TEST_USER_USERNAME=xxx@hospitalnet.hospital.gov.br and
every user logs in using username@hospital.gov.br, does not have the same domain.
I changed the LDAP_AUTH_TEST_USER_USERNAME account using a user with the same domain and it is working.
It really is insane that you put print (c.bind ()) to work.

**Comment by etianen** [comment]
Yeah, it's confusing as hell, but if you got it working, that's great!
