### ISSUE TITLE
Multiple LDAP Server

### ISSUE THREAD

**Issue by ghido** [etianen/django-python3-ldap#181]
Hi, for one my internal application i need to use two ldap server (AD) for manage the authentication of user on different active directory domain.
It's possibile to use django-python3-ldap ?
there are some documentations?
Thank you very much

Ghido

**Comment by etianen** [comment]
Multiple LDAP servers are not supported, sorry.

Docs here: https://github.com/etianen/django-python3-ldap/blob/master/README.rst
