### ISSUE TITLE
Access LDAP attributes after login

### ISSUE THREAD

**Issue by kevin-olbrich** [etianen/django-python3-ldap#183]
Hi!

Is it possible to get more information about the user logging into django?
For my application, I need more data from the user object (some attributes).
Using ldap3 I can access them very easily but it would be more easy to pull them from "request" just like "request.user" points to the User model.

Browsing the modules code I was unable to find such an integration.
Is it possible to pull this data anywhere without an own module?

Kind regards
Kevin

**Comment by kevin-olbrich** [comment]
As far as I understand the module, LDAP_AUTH_USER_FIELDS matches the values between the User model and LDAP attributes.

Is it possible to extend User by creating table with OneToOneField and link the additional field to LDAP_AUTH_USER_FIELDS?

**Comment by etianen** [comment]
To extend the user model:

https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#extending-the-existing-user-model

To map LDAP fields to your user model, use the settings:

LDAP_AUTH_USER_FIELDS
LDAP_AUTH_CLEAN_USER_DATA
LDAP_AUTH_SYNC_USER_RELATIONS

https://github.com/etianen/django-python3-ldap#available-settings

**Comment by kevin-olbrich** [comment]
Thank you very much! Will try this! I read the whole docs but still managed to read over this option!

**Comment by kevin-olbrich** [comment]
If someone every comes here and tries the same as me, here is an example:

Model:
https://bitbucket.org/code-orange/django-session-ldap-attributes/src/8c2173aff74e73587023f3150519243663fa1db4/django_session_ldap_attributes/models.py?at=master

LDAP_AUTH_SYNC_USER_RELATIONS function:
https://bitbucket.org/code-orange/django-session-ldap-attributes/src/d14167cb65e7df1d0bfc09b853d542ca24263add/django_session_ldap_attributes/ldap_func.py?at=master

In settings I set:
LDAP_AUTH_SYNC_USER_RELATIONS = "django_session_ldap_attributes.django_session_ldap_attributes.ldap_func.sync_user_relations"

Et voilà! I save a whole dump of the users attributes to a JSONField on every login. In my case this serves as a cache for applications functionality that depends on some info stored in LDAP attributes (for example extensionAttribute1 in Active Directory).

Thanks @etianen for help and this project!

**Comment by etianen** [comment]
Thanks for posting an example. That'll really help people out!
