### ISSUE TITLE
if  user's displayname isn't as the same as samaccountname, ldap authentication would be failed (AD)

### ISSUE THREAD

**Issue by hellotoday2** [etianen/django-python3-ldap#187]
aduser： d1u1
samaccountname: d1u1
displayename:d1_u1

************************************
from django.contrib.auth import authenticate
def ad_login(request):
    un=request.POST['username']
    pwd=request.POST['password']
    print("username: {0}".format(un))
    print("password: {0}".format(pwd))
    user = authenticate(username=un, password=pwd)
    if user:
        print("user: {0}".format(user))
    else:
        print("failed")

=============================
error message:
username: d1u1
password: China123
LDAP bind failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839  - bindResponse - None
failed

=============================
After just modifing the value of displayname attribute with samaccountname value (displayename:d1u1),  authentication sucess 

username: d1u1
password: China123
LDAP connect succeeded
LDAP user lookup succeeded
user: d1u1

**Comment by etianen** [comment]
I think you can just use `LDAP_AUTH_USER_FIELDS` to map the LDAP attribute to the Django username field.
