### ISSUE TITLE
Is it possible to sync users based on a group?

### ISSUE THREAD

**Issue by jcanning** [etianen/django-python3-ldap#192]
Hi all,

I am looking to sync users based on a group (CN) but it only appears to sync actual users accounts from an OU.

For example if use this as my search base, it syncs all the users in this OU:
LDAP_AUTH_SEARCH_BASE = "OU=Users,OU=Office,DC=Domain,DC=com"

However, I only want to sync users that are in a particular group to avoid extra work on the coding side to lock them out of the system.

For example, using this search base does not fail or throw an error but it also is not syncing any users in that group
LDAP_AUTH_SEARCH_BASE = "CN=Support,OU=DistributionGroups,DC=domain,DC=com"

Any thoughts on this would be appreciated.

Thanks,
JAC

**Comment by etianen** [comment]
Sounds like you want a custom user filter:

https://github.com/etianen/django-python3-ldap#custom-user-filters

**Comment by jcanning** [comment]
Hi @etianen,

That is exactly what i wanted, thanks! Follow up question, is there any way to disable the auto account creation? 

For example, i only want the users in this group to be able to log in and no one else.

Thanks,
JAC

**Comment by etianen** [comment]
Setting a user filter should prevent login or account creation for any user
in LDAP that doesn't match the filter.

Alternatively, you can use LDAP_AUTH_CLEAN_USER_DATA to set is_active to
False based on some criteria in the LDAP data.

**Comment by jcanning** [comment]
Awesome! Thanks a bunch Dave. This is such a great tool! 🥇
