### ISSUE TITLE
Group MAP search is case sensitiv

### ISSUE THREAD

**Issue by coredmp95** [etianen/django-python3-ldap#193]
Hello,

First, thanks a lot for this Apps, great job and very usefull. 

For the context, i am using the "LDAP_GROUP_MAP" functionality to syn AD group to Application group.

I just spend some time trying to figure out why it was not working for one particular ap, seems the search is case sensitive :

Not found :  CN=grp_cmdb_access-viewers,OU=IDM,OU=Applications Groups,dc=fab-lab,dc=local

Found  : CN=grp_cmdb_access-viewers,OU=IDM,OU=Applications Groups,DC=fab-lab,DC=local

I think the search should not be case sensisive as spec in : 
https://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx

Have a good day

**Comment by etianen** [comment]
django-python3-ldap just passes the search onto the LDAP server. I don't
think there's anything I can do to control this behavior. Maybe it's a
setting on the LDAP server?

**Comment by coredmp95** [comment]
Well, it is not the Ldap search that does'nt succeed as you can see in the logs : 

AUDIT BEGIN LOGIN PROCESS FOR: fabrice.didierjean
AUDIT SUCCESS LOGIN FOR: fabrice.didierjean
PROPOSITION PASSWORD: a*31#MC%QH
FAMILIES: 4
AUDIT LOGIN FOR: fabrice.didierjean USING LDAP GROUPS
AUDIT LOGIN FOR: fabrice.didierjean CLEANING OLD GROUP MEMBERSHIP
AUDIT LOGIN FOR: fabrice.didierjean DETECTED IN GROUP CN=grp_cmdb_access-admins,OU=IDM,OU=Applications Groups,DC=fab-lab,DC=local
AUDIT LOGIN FOR: fabrice.didierjean DENY ADMIN RIGHTS
AUDIT LOGIN FOR: fabrice.didierjean DENY STAFF RIGHTS
AUDIT LOGIN FOR: fabrice.didierjean DETECTED IN GROUP CN=grp_cmdb_access-editors,OU=IDM,OU=Applications Groups,DC=fab-lab,DC=local
AUDIT LOGIN FOR: fabrice.didierjean DENY ADMIN RIGHTS
AUDIT LOGIN FOR: fabrice.didierjean DENY STAFF RIGHTS
AUDIT LOGIN FOR: fabrice.didierjean DETECTED IN GROUP CN=grp_cmdb_access-viewers,OU=IDM,OU=Applications Groups,DC=fab-lab,DC=local
AUDIT LOGIN FOR: fabrice.didierjean DENY ADMIN RIGHTS
AUDIT LOGIN FOR: fabrice.didierjean DENY STAFF RIGHTS
AUDIT LOGIN FOR: fabrice.didierjean BEFORE MIN GROUP MEMBERSHIP


He found the group in the Ldap dir. But it doesn't add it to the django Group. It is because the ldap search is effectively not case sensitive. But you comparison is case sensitive here : 

```
                           # other groups membership
                                for grp in settings.LDAP_GROUPS_MAP.keys():
                                    if resp['dn'] == settings.LDAP_GROUPS_MAP[grp]:
                                        try:
                                            logger.info(grp)
                                            usr.groups.add(Group.objects.get(name=grp))
                                            logger.info("AUDIT LOGIN FOR: %s ADDING GROUP %s MEMBERSHIP" %
                                                        (username, grp))
                                        except ObjectDoesNotExist:
                                            pass
```

So if the ldap search with "dc" succeed, the comparison with the "DN"  given by the ldap server will failed. 

I thing that is you correct the comparison with something like this 👍 

if resp['dn'].lower() == settings.LDAP_GROUPS_MAP[grp].lower():

It will correct the problem, but i am clearly not a Python professional .. maybe something else could be more coherent

Best-Regards

**Comment by etianen** [comment]
Ah, I see.

LDAP_GROUP_MAP is not a part of django-python3-ldap. It's a code snippet that was shared by a user.

Your case-sensitive comparison is a good way to go about it.
