### ISSUE TITLE
Authenticate with Email or Username possible?

### ISSUE THREAD

**Issue by jcanning** [etianen/django-python3-ldap#204]
Hey, is it possible to authenticate users email or username?

I was looking to do what i would normally do which is create my own auth backend to accept emails and usernames but when i do that it fails on authenticating users that are in AD.

If I create a local user i can authenticate using both username or email.

I am guessing my local code won't matter but i'll add it anyways:

    from django.contrib.auth import get_user_model
    from django.contrib.auth.backends import ModelBackend
    from django.db.models import Q

    class EmailOrUsernameModelBackend(ModelBackend):
        def authenticate(self, request, username=None, password=None, **kwargs):
            user_model = get_user_model()

            if username is None:
                username = kwargs.get(user_model.USERNAME_FIELD)

            users = user_model._default_manager.filter(
                Q(**{user_model.USERNAME_FIELD: username}) | Q(email__iexact=username)
            )

            # Test whether any matched user has the provided password:
            for user in users:
                if user.check_password(password):
                    return user
            if not users:
                user_model().set_password(password)

**Comment by etianen** [comment]
The ldap auth backend uses bind() to authenticate a user, and I don't think
LDAP bind allows lookup via two credentials OR'd together.

**Comment by jcanning** [comment]
ohhh good point. Ok i will close this out then :) Thanks Dave!
