### ISSUE TITLE
Force auto_bind to be AUTO_BIND_NONE

### ISSUE THREAD

**Issue by meric** [etianen/django-python3-ldap#22]
In ldap.py, There's a bit of code that forces the use of auto_bind if user_identifier is present. (Which it will be given it's called in the authenticate method, where the username/email/id must always be given, and this is passed through to connection). I'm encountering a server that will not let me connect unless `auto_bind=AUTO_BIND_NONE`. Is there a workaround for this issue? 
```
if user_identifier:
        if settings.LDAP_AUTH_USE_TLS:
            auto_bind = ldap3.AUTO_BIND_TLS_BEFORE_BIND
        else:
            auto_bind = ldap3.AUTO_BIND_NO_TLS
    else:
        auto_bind = ldap3.AUTO_BIND_NONE
```

**Comment by etianen** [comment]
Are you connecting to an Active Directory server, or an OpenLDAP server?

**Comment by meric** [comment]
They also operate an adfs login service so I'm 98% sure it's Active Directory server.

**Comment by etianen** [comment]
Try using this branch:

https://github.com/etianen/django-python3-ldap/tree/active-directory-bind-support

And follow these configuration instructions:

https://github.com/etianen/django-python3-ldap/tree/active-directory-bind-support#microsoft-active-directory-support
