### ISSUE TITLE
Python2 retrocompatibility ?

### ISSUE THREAD

**Issue by NotSqrt** [etianen/django-python3-ldap#23]
Hi !

Just tested your module with python 2.7.
Apart from classes that have to inherit from ``object``, there does not appear to have too many things to fix to support python2.7.

Is that feasable ?

That would allow for a seamless upgrade from py2 to py3 for your users, and avoiding yet another dependency (``django-auth-ldap``, with its dependency on ``python-ldap``) ..

Thanks !

**Comment by etianen** [comment]
This module actually depends on python3-ldap, which is a python 3-only LDAP
module in pure Python.

So unfortunately I think it might be a lost cause... :(

**Comment by NotSqrt** [comment]
At https://github.com/cannatag/ldap3, the readme says "Python, Python 3, PyPy and PyPy3", and the travis file says it's tested on python 2.6 and 2.7 !!

**Comment by NotSqrt** [comment]
And simply by adding ``(object)`` to the classes in the conf module, I got these working :smile: :
* the 2 commands
* ability to log in the admin

**Comment by etianen** [comment]
Okay, I'll definitely look into this then!

Happy to take a pull request, or investigate it myself next week.
