### ISSUE TITLE
ldap_sync_users could deactivate user ?

### ISSUE THREAD

**Issue by jordiromera** [etianen/django-python3-ldap#238]
Hi,

First, thank you for this project and your work.

On several projects of mine, I wonder which is the best way to delete user account when, for example, people leave the firm.
What do you think about deactivate users deleted from LDAP, on Django side (rather than deleted them) ?
This clean step could be done every night for security purpose.

If you're ok with this idea, I can give a try to make un pull request.

Thank you

**Comment by etianen** [comment]
So I'd not delete the user, as that can cascade delete data associated with
the user too. Probably deactivating the user is correct.

I wonder though. Given the users are unable to login when deleted from
LDAP, what does disabling them in Django acheive?

**Comment by etianen** [comment]
I'd be happy to take an MR for a new command that deactivated user accounts.

Enjoy your hols!

**Comment by jordiromera** [comment]
PR has been merged, I close this issue
