### ISSUE TITLE
TLS does not work in current version/release

### ISSUE THREAD

**Issue by dblanque** [etianen/django-python3-ldap#249]
Hey _Etianen_! 

I've been developing an LDAP Management Tool with Django and VueJS and I wanted to let you know that LDAP over TLS (LDAPS) did not work properly in the current version of this module and I fixed it (along with making a fork of sorts) in my own project.

If you're interested I can send you the changes or you can check them out at [my project's LDAP Connector](https://github.com/dblanque/interlock-backend/blob/master/interlock_backend/ldap/connector.py#L154)

It's approximately at line 154. Currently using the **use_ssl** arg in the Server object.

Lemme know if I can help with anything,

Dylan

**Comment by dblanque** [comment]
I also added you to the contributing list for creating this module, thank you mate! 😄

**Comment by etianen** [comment]
Thanks! I'd love a PR that fixes it!

**Comment by dblanque** [comment]
Just added the PR, I first added the arg to the dictionary but then moved it to the **if settings.LDAP_AUTH_USE_TLS** conditional along with the TLS dictionary.

Hope that's useful mate!
