### ISSUE TITLE
mapping list to LDAP_AUTH_USER_FIELDS

### ISSUE THREAD

**Issue by richerzhagen** [etianen/django-python3-ldap#251]
my LDAP server has a list of groups for attribute "memberOf" but when I map the object as below only the first item of the list gets mapped

LDAP_AUTH_USER_FIELDS = {
  "username": "CN",
  "memberOf": "memberOf"
}

is there a way to map the entire list or search for a specific group before it gets mapped?

**Comment by etianen** [comment]
Check out the `LDAP_AUTH_CLEAN_USER_DATA` or `LDAP_AUTH_SYNC_USER_RELATIONS` settings:

https://github.com/etianen/django-python3-ldap/#available-settings
https://github.com/etianen/django-python3-ldap/#sync-user-relations
