### ISSUE TITLE
Incorrect username comparison causes redundant rebind 

### ISSUE THREAD

**Issue by gagantrivedi** [etianen/django-python3-ldap#256]
Firstly, thanks for the amazing work!
Now, Here: https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L214 `settings.LDAP_AUTH_CONNECTION_USERNAME` is never going to be equal to `username` since `username` here is formatted, but we format `settings.LDAP_AUTH_CONNECTION_USERNAME` after comparison resulting in a redundant rebind, unless I am missing something (which is entirely possible :) ) ?

**Comment by etianen** [comment]
You appear to be completely correct.

I'd take a bugfix PR for this, if you feel up to it? :pray:

**Comment by etianen** [comment]
I see you have in #257

**Comment by etianen** [comment]
I'll make a new release with the bugfix today
