### ISSUE TITLE
Can't find user when use [^a-zA-Z0-9_\-] characters in username

### ISSUE THREAD

**Issue by Quazer** [etianen/django-python3-ldap#26]
I have usernames as "Pupkin.V.I", and search query failed, becouse (line 98 *ldap.py*):
```python
field_value = clean_ldap_name(field_value),
```

When i changed to 
```python
field_value = field_value, # clean_ldap_name(field_value),
```
query is success

**Comment by etianen** [comment]
Have you tried using the master branch? This should be fixed.

**Comment by etianen** [comment]
I'm closing this, due to inactivity.
