### ISSUE TITLE
Stuck during authentication

### ISSUE THREAD

**Issue by JasonLee93** [etianen/django-python3-ldap#266]
Hello, thank you for providing the great package in first.

My app stuck during ldap authentication, it seems not woking, I only see a rotating spinner in the browser, and nothing happens.
I used multiple AUTHENTICATION_BACKENDS as below
`AUTHENTICATION_BACKENDS = (
    "django_python3_ldap.auth.LDAPBackend",
    'django.contrib.auth.backends.ModelBackend',
)`
I try to create a new .py file to do testing, I use the ldap3 library directly, it works fine and connect to the ldap server successfully.
Then I try to enable logging in the settings.py to know where is geting stuck, but I still haven't seen any information output

**Comment by MaykCheck** [comment]
hello, how did you solve it?
