### ISSUE TITLE
_get_or_create_user: user_data["attributes"] - key error

### ISSUE THREAD

**Issue by jjagielka** [etianen/django-python3-ldap#32]
ldap search can return different kinds of responses: 
 - type `searchResEntry` - it contains the `attributes` key, all good
 - type `searchResRef` - `attributes` key is not present, and then `_get_or_create_user` will raise an error.

It's especially valid for `iter_users` when both types can be present.

Quick workaround for `iter_users`:
``` python
return (
    self._get_or_create_user(entry)
    for entry
    in paged_entries if entry["type"] == "searchResEntry"
)
```

**Comment by morrei** [comment]
Are you using ActiveDirectory?

**Comment by jjagielka** [comment]
Yes. That's the case.

Jakub


-----Original Message-----

**Comment by etianen** [comment]
What does a searchResRef represent?

**Comment by jjagielka** [comment]
I believe those are the trees that were searched.
```
{'type': 'searchResRef', 'uri': ["b'ldap://host/CN=Configuration,DC=x,DC=y'"]}
{'type': 'searchResRef', 'uri': ["b'ldap://DomainDnsZones.x.y/DC=DomainDnsZones,DC=x,DC=y'"]}
{'type': 'searchResRef', 'uri': ["b'ldap://ForestDnsZones.x.y/DC=ForestDnsZones,DC=x,DC=y'"]}
```
Those are followed by normal `searchResEntry` records.

**Comment by jjagielka** [comment]
According to https://tools.ietf.org/html/rfc4511

    searchRequest         SearchRequest,
    searchResEntry        SearchResultEntry,
    searchResDone         SearchResultDone,
    searchResRef          SearchResultReference,

**4.5.2.  Search Result**
The results of the Search operation are returned as zero or more `SearchResultEntry` and/or `SearchResultReference` messages, followed by a single `SearchResultDone` message.

        SearchResultEntry ::= [APPLICATION 4] SEQUENCE {
             objectName      LDAPDN,
             attributes      PartialAttributeList }

        PartialAttributeList ::= SEQUENCE OF
                             partialAttribute PartialAttribute

        SearchResultReference ::= [APPLICATION 19] SEQUENCE
                                  SIZE (1..MAX) OF uri URI

        SearchResultDone ::= [APPLICATION 5] LDAPResult
