### ISSUE TITLE
base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprecated

### ISSUE THREAD

**Issue by RosesDurden** [etianen/django-python3-ldap#38]
Hi,

I just configured my settings.py as following : 

```
LDAP_AUTH_URL = 'ldap://ldap-icd.app.myLDAP.com:389'

LDAP_AUTH_SEARCH_BASE = "dc=Internal,dc=Users,dc=root"

LDAP_AUTH_OBJECT_CLASS = "*"

LDAP_AUTH_USER_FIELDS = {
    "username": "uid",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

LDAP_AUTH_USER_LOOKUP_FIELDS = "username"

LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_openldap"

LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_PASSWORD = None
```

And when I call it from my command line : `py manage.py ldap_sync_users`
I got the following error : 

`C:\Python27\lib\site-packages\django\core\management\base.py:577: RemovedInDjang
o110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.1
0. Use BaseCommand instead, which takes no arguments by default.
  RemovedInDjango110Warning`

Do you have any idea why I'm facing this issue?
Thanks

**Comment by etianen** [comment]
That's not an error, just a warning. You can ignore it.

**Comment by RosesDurden** [comment]
Well it's not the right solution but I think it's not a big deal, thanks.

**Comment by etianen** [comment]
How not the right solution? The warning implies that the
django-python3-ldap is using a feature that will be removed in Django 1.11,
which is two versions away. Part of supporting multiple versions of Django
is balancing the use of features pending deprecation versus using features
that will break backwards-compatibility.
