### ISSUE TITLE
Issue with the admin interface

### ISSUE THREAD

**Issue by RosesDurden** [etianen/django-python3-ldap#39]
Hi, first, I would like to thank you for your nice work. It's a pain in the .. to work with LDAP.

I just follow your instructions and your configuration like this : 

````
AUTHENTICATION_BACKENDS = (
    'django_python3_ldap.auth.LDAPBackend'
)
LDAP_AUTH_URL = 'ldap://ldap-icd.app.my-ldap.com:389'
LDAP_AUTH_USE_TLS = False
LDAP_AUTH_SEARCH_BASE = "dc=Internal,dc=Users,dc=root"
LDAP_AUTH_OBJECT_CLASS = "person"
LDAP_AUTH_USER_FIELDS = {
     "username": "uid",
}

LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_openldap"
LDAP_AUTH_CONNECTION_USERNAME = "uid=reader.myAPP,dc=Services,dc=Users,dc=root"
LDAP_AUTH_CONNECTION_PASSWORD = "myPass"
```

When I execute `python manage.py ldap_sync_users` it's okay, all the username appears on the screen but when I try to logging through the administration interface, it's not working. My error message : 

> Please enter a correct username and password. Note that both fields are case-sensitive

I'm sure that both username and password are correct.

Any idea? Thanks

**Comment by etianen** [comment]
The created users do not have admin permission by default.

You can use the `./manage.py ldap_promote your_username` to grant admin
access to a single user.

**Comment by RosesDurden** [comment]
Hi, thanks for the answer. I tried to promote me as superuser and it's still unsuccessfull. 
Same error message on the login screen.

**Comment by etianen** [comment]
So, things to check:

1. Use the django shell to confirm your user has is_staff and is_superuser
set.
2. Is your LDAP server OpenLDAP or Active Directory?

**Comment by RosesDurden** [comment]
Well, after checking that my user is also staff and superuser : 

```
>>> from django.contrib.auth.models import User
>>> user = User.objects.get(username='myUsername')
>>> user.is_staff
True
>>> user.is_superuser
True
```

I think that my LDAP Server is finally an Active Directory so I tried to set it as following : 

```
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

# Sets the login domain for Active Directory users.
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "CORP"

# The LDAP username and password of a user for authenticating the `ldap_sync_users`
# management command. Set to None if you allow anonymous queries.
LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_PASSWORD = None
```

But still doesn't work when trying to login.

**Comment by RosesDurden** [comment]
Also I tried to connect with SSL port : 

```
LDAP_AUTH_URL = 'ldap://ldap-icd.myApp.com:636'

LDAP_AUTH_USE_TLS = True

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

# Sets the login domain for Active Directory users.
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "corp"

# The LDAP username and password of a user for authenticating the `ldap_sync_users`
# management command. Set to None if you allow anonymous queries.
LDAP_AUTH_CONNECTION_USERNAME = "uid=reader.myapp,dc=Services,dc=Users,dc=root"
LDAP_AUTH_CONNECTION_PASSWORD = "myPass"
```

And still doesn't work, but I have an other error : 
```
LDAPSessionTerminatedByServerError at /admin/login/
session terminated by server
```

**Comment by etianen** [comment]
Try with the SSL port, and the LDAP_AUTH_URL set to 'ldaps://
ldap-icd.myApp.com:636'

**Comment by etianen** [comment]
(Notice the ldap***s*** bit)

**Comment by RosesDurden** [comment]
Hum, I just used a software who show me that it's an OpenLDAP (v2.4) that I use.
So my config in the first place was OK, right?

When I check the users in the admin interface, I have the following : 

- MyUserAccount : No password defined..

**Comment by etianen** [comment]
Your original config was probably correct, yes.

The LDAP auth backend does not store user passwords in the DB, as the authentication is done via LDAP bind, so that's expected.

I think it's time for your to dig into the ldap3 library and find out why it's refusing the bind. Something like this:

``` py
import ldap3
with ldap3.Connection(ldap3.Server("ldap://ldap-icd.app.my-ldap.com:389"), user="uid=myUsername,dc=Services,dc=Users,dc=root", password="myPass", auto_bind=ldap3.AUTO_BIND_NO_TLS) as connection:
    print(connection)
```

Play around with different values for auto_bind and the LDAP URL. See what exceptions you get. Some combination should allow you to bind, since you're able to login with your LDAP_AUTH_CONNECTION_USERNAME in order to sync users.

**Comment by RosesDurden** [comment]
First, I get the following exception : `tls not started`

So I just wrote the following : 

```
with ldap3.Connection(ldap3.Server("ldap://ldap-icd.app.ale-international.com:389"),user="uid=reader.licops,dc=Services,dc=Users,dc=root", password="qBS@*6n2", auto_bind=True) as connection:
	connection.start_tls()
	print(connection)
```
And now I have this exception : 

```
True
ldap://ldap-icd.app.my-app.com:389 - cleartext - user: uid=my.username,dc=Services,dc=Users,dc=root - bound - open - <local: LocalIP:57795 - remote: RemoteIP:389> - tls started - listening - SyncStrategy - internal decoder
```

So I think with the manual TLS start it will work, right?

**Comment by etianen** [comment]
Hmm, so in your project settings try LDAP_AUTH_USE_TLS = True

**Comment by RosesDurden** [comment]
Yep I tried and it still doesn't work.
My settings : 

```
LDAP_AUTH_URL = 'ldap://ldap-icd.app.my-app.com:289'
LDAP_AUTH_USE_TLS = True
LDAP_AUTH_SEARCH_BASE = "dc=Internal,dc=Users,dc=root"
LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"
LDAP_AUTH_USER_FIELDS = {
    "username": "uid",
}

LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_openldap"
LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_PASSWORD = None
```
With those settings, the ldap_sync_users work and the ldap_promote command works but the login still don't.

So I also tried to set credentials : 

```
LDAP_AUTH_CONNECTION_USERNAME = "uid=reader.myapp,dc=Services,dc=Users,dc=root"
LDAP_AUTH_CONNECTION_PASSWORD = "myPass"
```
With both port 636 and 389.

But then the ldap_sync_users doesn't work : 

```
for user in connection.iter_users():
AttributeError: 'NoneType' object has no attribute 'iter_users'
```

**Comment by etianen** [comment]
Hmm, I guess it's time to pick open the django-python3-ldap code and add
some debugging.

Try printing the stack trace of the exception here:
https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L132

I suspect adding some logging to django-python3-ldap would be a good
feature...

**Comment by RosesDurden** [comment]
I'm not sure what you really want me to print. I printed the username, the password and the auto_bind values and get exactly what I expected, which is : 

```
(username) --> uid=uid\3Dreader.myapp\2Cdc\3DServices\2Cdc\3DUsers\2Cdc\3Droot,dc=Internal,dc=
Users,dc=root
(password) --> qBS@*6n2
(auto_bind) --> TLS_BEFORE_BIND
```

What I did in python shell : 

```
>>> def connection(**kwargs):
    # Format the DN for the username.
    kwargs = {
        key: value
        for key, value
        in kwargs.items()
        if value
    }
    username = None
    password = None
    if kwargs:
        password = kwargs.pop("password")
        username = import_func(settings.LDAP_AUTH_FORMAT_USERNAME)(kwargs)
    # Make the connection.
        auto_bind = True
    try:
        with ldap3.Connection(ldap3.Server("ldap://ldap-icd.app.my-app.com:389"), user="uid=reader.myapp,dc=Services,dc=Users,dc=root", password="myPass", auto_bind=auto_bind) as c:
		yield ldap3.Connection(c)
    except (ldap3.LDAPBindError, ldap3.LDAPSASLPrepError):
        yield None

>>> co = connection()
>>> for i in co:
	print(i)
```

And the result : 
`ldap://ldap-icd.app.my-app.com:389 - cleartext - user: uid=reader.myApp,dc=Services,dc=Users,dc=root - bound - open - <local: LocalIP:60097 - remote: remoteIP:389> - tls not started - listening - SyncStrategy - internal decoder - user: None - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder`

**Comment by etianen** [comment]
I'm suggesting that you modify the source code of django-python3-ldap, and
replacing these two lines:

https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L131
https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L132

With:

except (ldap3.LDAPBindError, ldap3.LDAPSASLPrepError) as ex:
    print(ex)
    yield None

**Comment by RosesDurden** [comment]
I just did it and tried to ldap_sync_users and get the following : 

[29/Feb/2016 15:55:28] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1968
automatic bind not successful - invalidCredentials

I will dig into this issue and try to make it work.

**Comment by RosesDurden** [comment]
After a few hours searching I  think that my proxy and/or my firewall are making troubles. Any idea how to set credentials for proxy or disable firewall?

**Comment by etianen** [comment]
Surely that has to be done in your operating system?

In your first email, you said that you managed to make ldap_sync_users
work. This implies that the connection is fine. Trying to get
ldap_sync_users to work with an LDAP_AUTH_CONNECTION_USERNAME
and LDAP_AUTH_CONNECTION_PASSWORD set is a good place to start.

**Comment by krutaw** [comment]
I know this is a little late, but I was having the exact same issue, I commented out LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN to resolve it.
