### ISSUE TITLE
Certificate validation

### ISSUE THREAD

**Issue by NotSqrt** [etianen/django-python3-ldap#40]
Hi,

Certificate validation is rather simple :

``` python
import ssl  # standard library
import certifi  # new dependency

tls = ldap3.Tls(validate=ssl.CERT_REQUIRED, ca_certs_path=certifi.where())  # optionally: version=ssl.PROTOCOL_TLSv1_2
server = ldap3.Server(settings.LDAP_AUTH_URL, tls=tls)
ldap3.Connection(server, user=username, password=password, auto_bind=auto_bind) as c:
```

I guess it requires a few settings to be flexible.

There's something I don't understand: `auto_bind` is forced to `AUTO_BIND_NONE` in anonymous mode (eg when running ldap_sync_users), even with `LDAP_AUTH_USE_TLS=True`

Thanks !

**Comment by NotSqrt** [comment]
Security by default would be a nice choice, even if it was not the case for a long time in Python : very few checks when fetching ``https`` urls with the standard library for instance. ``python-requests`` is a good example.

**Comment by etianen** [comment]
I don't think we can turn on certificate validation by default, as a lot of
people use homebrewed LDAP setups, but it would be nice to have a hook to
turn it on. Maybe an LDAP_TLS_VALIDATE=True setting?

Does having AUTO_BIND_NONE prevent TLS? My understanding was that it simply
didn't attempt an LDAP bind operation, which is separate from TLS.

**Comment by NotSqrt** [comment]
Certificate validation by default: I would really consider security first, and explicit disabling of verifications : a good reading is this issue from python-requests when urllib3 added a warning when disabling verification : https://github.com/kennethreitz/requests/issues/2214

It is now fairly easy (and free) to add full-chain verifiable certificates with let's encrypt, and these certificates work with LDAP.
For test systems, people can do what they want, but for production systems, it's time to do security properly ! (Gmail warning about insecure SMTP connections when sending an email to gmail -> 25% less insecure SMTP connections in just a few weeks !)



For auto_bind:

Yes, having AUTO_BIND_NONE prevents TLS/start_tls.

This is the code in ``Connection.__init__``:
```python
if self.auto_bind and self.auto_bind != AUTO_BIND_NONE:
    if self.auto_bind == AUTO_BIND_NO_TLS:
        self.bind(read_server_info=True)
    elif self.auto_bind == AUTO_BIND_TLS_BEFORE_BIND or auto_bind is True:
        self.start_tls(read_server_info=False)
        self.bind(read_server_info=True)
    elif self.auto_bind == AUTO_BIND_TLS_AFTER_BIND:
        self.bind(read_server_info=False)
        self.start_tls(read_server_info=True)
```

and there are no other call to ``start_tls``.

From the content of ``Connection.bind``, it's perfectly legal to use ``AUTO_BIND_TLS_BEFORE_BIND`` with anonymous connections.

**Comment by etianen** [comment]
From that code snippet, it looks like AUTO_BIND_TLS_BEFORE_BIND will still
result to a call to self.bind(). Won't this result in a ldap3.LDAPBindError
if this is an anonymous connection?

In terms of default certificate validation, the issue with turning it on
now is that it will break people's sites on upgrade, in a way that will for
many only manifest in production (running with LDAP auth turned off in
development is a pretty useful way of making automated tests run in a
sensible amount of time). I think maybe a long transition period of it
being default off, and generate a warning, is required, before a switch to
default on.

**Comment by NotSqrt** [comment]
Ok for a "transition period of default off, and generate a warning, before a switch to
default on" ! :+1: 

A ``bind``, even anonymous, is always going to be executed at some point.
This is a small portion of the debug log of ``ldap3``, when running ``python manage.py ldap_sync_users``:
```
DEBUG:ldap3:BASIC:start BIND operation via <ldap://server:389 - cleartext - user: None - unbound - open - <local: client_ip:52263 - remote: server_ip:389> - tls not started - listening - SyncStrategy - internal decoder>
DEBUG:ldap3:PROTOCOL:performing anonymous BIND for <ldap://server:389 - cleartext - user: None - unbound - open - <local: client_ip:52263 - remote: server_ip:389> - tls not started - listening - SyncStrategy - internal decoder>
DEBUG:ldap3:PROTOCOL:anonymous BIND request <{'authentication': {'simple': '', 'sasl': None}, 'version': 3, 'name': ''}> sent via <ldap://server:389 - cleartext - user: None - unbound - open - <local: client_ip:52263 - remote: server_ip:389> - tls not started - listening - SyncStrategy - internal decoder>
```

In your ``connection``, removing the check for anonymous connections and activating ``AUTO_BIND_TLS_BEFORE_BIND`` when ``LDAP_AUTH_USE_TLS`` is True  works with my server (openldap on a ubuntu 12.04 server):
```python
    # if username or password:
        if settings.LDAP_AUTH_USE_TLS:
            auto_bind = ldap3.AUTO_BIND_TLS_BEFORE_BIND
        else:
            auto_bind = ldap3.AUTO_BIND_NO_TLS
    # else:
        # auto_bind = ldap3.AUTO_BIND_NONE
```

**Comment by etianen** [comment]
Okay, so I've fixed the TLS issue in 6373984359a177234f2746560af5ac8b7ef02ede . Thanks for your work in figuring this out!

I'll also take a pull request for:

- LDAP_AUTH_TLS_VALIDATE setting, defaulting to False
- A FutureWarning("LDAP_AUTH_TLS_VALIDATE will default to True in a future release of django-python3-ldap. Please set LDAP_AUTH_TLS_VALIDATE = False in your settings.py file to keep the current behavior.") raised if the setting is unset.

Alternatively, I'll add that feature myself at some point when I have more free time in the future.

**Comment by NotSqrt** [comment]
Great !

For the warning and the transition period:

``settings.LDAP_CERTIFICATE_VERIFY`` can be ``None`` by default, corresponding to no verification, with the warning saying to either use 
- ``False`` for no validation, 
- ``True`` for default validation against ``certifi.where()`` for instance, 
- specific file or folder for validation against a stored certificate (typically, a self-signed certificate) or a folder of authorized intermediate CAs.

At the end of the transition period, ``LDAP_CERTIFICATE_VERIFY is None`` can switch to the same behaviour than ``True``

**Comment by etianen** [comment]
It might be cleaner to have another setting to configure ca_certs_path,
rather than overload a setting. Other than that, I agree heartily.

**Comment by michaelcalve** [comment]
I have an active directory cert file. Is there a way to include its path for LDAP config? 

I guess I'm confused as to how this is implemented per this discussion.

**Comment by etianen** [comment]
This idea was never implemented, sadly.

**Comment by Sogetsue** [comment]
IS there any way currently to add certificate validation?

**Comment by etianen** [comment]
I guess someone's gotta implement the idea.
