### ISSUE TITLE
user passwords is not sync | users only created at sync not at login

### ISSUE THREAD

**Issue by madsholme** [etianen/django-python3-ldap#42]
I have ben trying to get this working on a small site, with ad integration. I have come as far as i have it importing my users just fine, but i cant seem to be able to log into the site with them.

i have these settings in my settings.py and as i said i can sync the users just fine. But when i look at them in the django admin, it says their passwords are empty/not set?

````
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'django_python3_ldap.auth.LDAPBackend',
    )`

`#LDAP START

# The URL of the LDAP server.
LDAP_AUTH_URL = "ldap://10.10.0.21:389"

# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = False

# The LDAP search base for looking up users.
LDAP_AUTH_SEARCH_BASE = "OU=.site.local,DC=site,DC=local"
                        
# The LDAP class that represents a user.
#LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"
LDAP_AUTH_OBJECT_CLASS = "organizationalPerson"
# User model fields mapped to the LDAP
# attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# A tuple of django model fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

# Path to a callable that takes a dict of {model_field_name: value},
# returning a dict of clean model data.
# Use this to customize how data loaded from LDAP is saved to the User model.
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

# Path to a callable that takes a user model and a dict of {ldap_field_name: [value]},
# and saves any additional user relationships based on the LDAP data.
# Use this to customize how data loaded from LDAP is saved to User model relations.
# For customizing non-related User model fields, use LDAP_AUTH_CLEAN_USER_DATA.
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

# Path to a callable that takes a dict of {ldap_field_name: value},
# returning a list of [ldap_search_filter]. The search filters will then be AND'd
# together when creating the final search filter.
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

# Path to a callable that takes a dict of {model_field_name: value}, and returns
# a string of the username to bind to the LDAP server.
# Use this to support different types of LDAP server.
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

# Sets the login domain for Active Directory users.
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = None

# The LDAP username and password of a user for authenticating the `ldap_sync_users`
# management command. Set to None if you allow anonymous queries.
LDAP_AUTH_CONNECTION_USERNAME = 'yyyyy@site.local'
LDAP_AUTH_CONNECTION_PASSWORD = 'xxxxxx'

#LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "site.local"
#LDAP SLUT`
```

If i manualy define a password for the user in admin page, i can login just fine... so what am i missing?

i also tried to map the password field like this with no luck

```
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
    "password": "userPassword",
}
```

Another isue i have, is the users is only being created when i use the sync command, not when they try to login? do i need to add anything to my views.py?

**Comment by madsholme** [comment]
mabye i am missing somethign on  my login code? do i need to change the auth part there?

```
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
```

**Comment by kmvinoth** [comment]
Hi madsholme

Firstly, The passwords from the LDAP server are not stored in the local
django database (auth_user table) even though you sync users.

Django local user will have the password hash starting from *pbkdf2_* while
ldap user will have something different.


For your login, you can use the (builtin) views from
djangocontrib.auth.views.login and it takes care of the authentication, but
you have to provide a template for this (see django documentation for more
details). Hope this information helps.

Regards
Vinothkumar



On Mon, Jun 20, 2016 at 11:53 PM, madsholme <notifications@github.com>
wrote:

> mabye i am missing somethign on my login code? do i need to change the
> auth part there?
>
>     username = request.POST.get('username', '')
>     password = request.POST.get('password', '')
>     user = auth.authenticate(username=username, password=password)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/etianen/django-python3-ldap/issues/42#issuecomment-227281381>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AG4RHQ-EdGGuYC2ouiAWaP4H75M0iCTmks5qNwvGgaJpZM4I6JoL>
> .
>



-- 
Regards
Vinothkumar Mohanakrishnan

**Comment by madsholme** [comment]
hi kmvinoth

Thanks for your reply..

I figured out that much, and i have a login form, i was using with the built in user model in django, that worked just fine. It was my understanding that it would work aswell with this ldap module, with out i have to change anything? I have posted it on the above post.

for some reason the users sync just fine, but i cant get the login part to work...

**Comment by etianen** [comment]
Try updating to django-python3-ldap 0.9.10, then enable logging:

https://github.com/etianen/django-python3-ldap#logging

You should see some debug information come up in your console.

**Comment by madsholme** [comment]
I think i am getting close...

```
>>> u = ldap.authenticate(username="user@domain.local", password="wrongcode")
LDAP login failed: automatic bind not successful - invalidCredentials
>>> type(u)
<class 'NoneType'>

>>> u = ldap.authenticate(username="user@domain.local", password="correct code")
>>> type(u)
<class 'NoneType'>
```

I have to use the domain.local after my user. 

when i use the correct user and code, there is no response, as you can see there is a response when its wrong.. but if i do a type on in, i still get NoneType, and the login form dosent work..

**Comment by madsholme** [comment]
it seems that i can log in with my mail address now though.. i need to test this... :)

**Comment by madsholme** [comment]
it works just fine now..

when hosting the website on iis, it seems thought the ldap auth dosent work. if i start the same site, with manage.py it works just fine... any way to debug this?

if i create a user manualy in the admin site, it works just fine.

**Comment by etianen** [comment]
You can debug the LDAP connection by updating to django-python3-ldap 0.9.10, then enable logging:

https://github.com/etianen/django-python3-ldap#logging

You should see some debug information come up in your console.

**Comment by madsholme** [comment]
But that only works when its running from manage.py runserver? when its set up as a fastcgi app in IIS 7.5 you dont get a console... I dont think its an error on your part, i just hoped someone had tried the same and knew what the isue is...

**Comment by etianen** [comment]
Ah, so you can configure Django logging in all sorts of ways!

https://docs.djangoproject.com/en/1.9/topics/logging/

In your case, this should work:

``` py
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/path/to/django/debug.log',
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["file"],
            "level": "INFO",
        },
    },
}
```

**Comment by etianen** [comment]
(You'll want to set the correct log filename, of course!)

**Comment by madsholme** [comment]
Perfect... i found the isue, i had to change application pool idendity of the iis site running the django code.. i set it as system, and now the login thing works. thanks for all your help.

**Comment by etianen** [comment]
I have no idea about the meaning of what you just said, but I'm glad it's
working! :D

Honestly, LDAP is cryptic nonsense to me, but I needed to integrate with an
LDAP server at work, and nothing else worked in Python 3 at the time. :P
