### ISSUE TITLE
Failover to local accounts?

### ISSUE THREAD

**Issue by smills2929** [etianen/django-python3-ldap#44]
Is there any way to use local Django username/password details if the LDAP login fails?

I'd like to have some standard admin and management logins regardless of the LDAP server being used.

**Comment by smills2929** [comment]
Disregard.

This is how you do it:
AUTHENTICATION_BACKENDS = [
    'django_python3_ldap.auth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend'
]

**Comment by etianen** [comment]
Even better, put them the other way around and you can still log in with
your admin logins if the LDAP server is down!

It also lets you override the LDAP password with a local one.
