### ISSUE TITLE
calls to ldap.connection(username=..., password=...) are restrictive

### ISSUE THREAD

**Issue by audiolion** [etianen/django-python3-ldap#45]
edit: a solution to this is to just override `LDAP_AUTH_FORMAT_USERNAME` but I wonder if a change to how we map these values would just be a more general and applicable solution?

Hey @etianen!

Thank you for all the work you have done on this library. I encountered an issue today when setting it up. The command `ldap_sync_users` calls `ldap.connection(username=...` making it so if you have a `username` Django **field** that has a different label than `username` it will produce an error in `utils.py L#38` when it tries to pop `username` from the `LDAP_AUTH_USER_FIELDS` and it doesn't find the key `username`.

In my instance my `username` is defined as `university_username` in my Django **Model**

I am trying to think of how this could be generalized, it would require that we either accept a command line argument that represents the `username` field in our model with the default fallback being `username` _or_ we look into `LDAP_AUTH_USER_FIELDS` and take they keyword from there. The problem is I am not sure how we can always know which field would link to username, because what if the user model was based on `email` as the username or another field.

I guess the issue here is authenticating to ldap with a username and password correlates to the `LDAP_AUTH_USER_FIELDS` and it probably shouldn't have that dependency.

I think maybe the best thing to do would be provide an additional setting that you can apply that maps the ldap `username` to the model field

**---**

Clarification as I have learned more about django-python3-ldap

Suppose a Django custom user model:

``` python
class User(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'email'

    email = models.EmailField(unique=True)
    university_username = models.CharField(
        verbose_name="Username",
        max_length=255,
        unique=True,
    )
```

Then the following mappings would apply:

``` python

LDAP_AUTH_USER_LOOKUP_FIELDS = ("email",)
LDAP_AUTH_USER_FIELDS = {
    "email": "mail",
    "university_username": "uid"
}
```

So pretty standard except instead of `username` we have `university_username`, here is where the problems start to occur.

``` python
# ldap_sync_users.py

class Command(BaseCommand):

    help = "Creates local user models for all users found in the remote LDAP authentication server."

    @transaction.atomic()
    def handle(self, *args, **kwargs):
        verbosity = int(kwargs.get("verbosity", 1))
        # passing in kwarg dict with key username NOT university_username
        with ldap.connection(username=settings.LDAP_AUTH_CONNECTION_USERNAME, password=settings.LDAP_AUTH_CONNECTION_PASSWORD) as connection:
            for user in connection.iter_users():
                if verbosity >= 1:
                    self.stdout.write("Synced {user}".format(
                        user = user,
                    ))
```

This causes issues when we are trying to later pop and map the fields in `utils.py`

``` python

def convert_model_fields_to_ldap_fields(model_fields):
    """
    Converts a set of model fields into a set of corresponding
    LDAP fields.
    """
    print "convert_model", model_fields
    print settings.LDAP_AUTH_USER_FIELDS
    return {
        # field_name will get 'username' when the dict contains 'university_username', KeyError results
        settings.LDAP_AUTH_USER_FIELDS[field_name]: field_value
        for field_name, field_value
        in model_fields.items()
    }
```

Now assuming for sake of argument we modify the `ldap_sync_users.py` with this hack so we get past this issue

``` python

@transaction.atomic()
    def handle(self, *args, **kwargs):
        verbosity = int(kwargs.get("verbosity", 1))
        # we simply assign university_username to kwarg so that it matches appropriately and can move on
        with ldap.connection(university_username=settings.LDAP_AUTH_CONNECTION_USERNAME, password=settings.LDAP_AUTH_CONNECTION_PASSWORD) as connection:
```

Everything should work fine now. The question is can we generalize so that if you change the `username` field in your model it will pass in the appropriate `kwarg` in the command?

**Comment by etianen** [comment]
If I understand your use-case correctly, the configuration you need is:

``` py
# The university username unique identifies the model in both the database and LDAP.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("university_username",)

# Map model fields to LDAP fields.
LDAP_AUTH_USER_FIELDS = {
    "email": "mail",
    "university_username": "uid"
}
```

You then call:

``` py
authenticate(university_username="foo", password="bar")
```

Which will then call:

``` py
connection(university_username="foo", password="bar")
```

Which will then attempt to bind to the ldap server with:

``` py
ldap3.Connection(ldap3.Server(settings.LDAP_AUTH_URL), user="uid=foo", password="bar". auto_bind=auto_bind)
```

**Comment by audiolion** [comment]
Agreed that using `authenticate()` works for this, and `connection()` also allows for variable kwargs.

The problem here is that if I want to run the management command `ldap_sync_users` it will fail because it always passes in `username` kwarg to the `connection()` function. I can't pass in modified `**kwargs` to the `ldap_sync_users` command nor does it pull the modified `kwargs` based on the `LDAP_AUTH_USER_LOOKUP_FIELDS` setting or `LDAP_AUTH_USER_FIELDS` dictionary.

```python
class Command(BaseCommand):

    help = "Creates local user models for all users found in the remote LDAP authentication server."

    @transaction.atomic()
    def handle(self, *args, **kwargs):
        verbosity = int(kwargs.get("verbosity", 1))
        # always passes in username, command doesn't allow for a different kwarg
        with ldap.connection(username=settings.LDAP_AUTH_CONNECTION_USERNAME, password=settings.LDAP_AUTH_CONNECTION_PASSWORD) as connection:
```

**Comment by etianen** [comment]
Ah, I see.

I think a new setting is needed:

``` p
LDAP_AUTH_CONNECTION_KWARGS = {}
```

This will replace `LDAP_AUTH_CONNECTION_USERNAME` and `LDAP_AUTH_CONNECTION_PASSWORD`, and be passed to the `ldap.connection()` call in `ldap_sync_users`.

I'm happy to take a pull request for this. The docs would need to be updated too. I'm not sure that deprecation warnings are really needed here, as it's not a critical piece of functionality, and deprecations are a huge maintenence burden.

**Comment by audiolion** [comment]
Yeah ill update it for you
