### ISSUE TITLE
where can I set the ldap bind password？

### ISSUE THREAD

**Issue by iMuYi** [etianen/django-python3-ldap#47]
Thanks for your all work！
When I use django_auth-ldap, I set the password by `AUTH_LDAP_BIND_PASSWORD='123456'`, but I don't find how to do it in your work.

**Comment by etianen** [comment]
The user provides the bind password when they log in. That's how they authenticate.

Or do you mean the password for downloading the list of users? That's the `LDAP_AUTH_CONNECTION_PASSWORD` setting.

https://github.com/etianen/django-python3-ldap#available-settings
