### ISSUE TITLE
LDAP_AUTH_FORMAT_USERNAME = lambda x: x['username']

### ISSUE THREAD

**Issue by davidkwast** [etianen/django-python3-ldap#51]
It took one hour to figure this out, so I will leave it here for a documentation enhancement proposal.

Maybe other people will have to this

```
LDAP_AUTH_CONNECTION_USERNAME = 'cn=admin,dc=example,dc=com'
LDAP_AUTH_FORMAT_USERNAME = lambda x: x['username']
LDAP_AUTH_SEARCH_BASE = 'ou=users,dc=example,dc=com'
```

I don't know enough about LDAP and related protocols, but in my case I had to provide a quick fix to the login credentials in the Django settings file.

If I didn't done the right adjustment, please someone tell me.

**Comment by TroyMurphy** [comment]
I have also been playing with this for the better part of a day. I think I found a better solution. By doing x['username'] you must be passing a full distinguished name each time, which defeats the purpose of the search base.

If you have access to the LDAP server, check the distinguished name for users. Make sure that the "username" key in LDAP_AUTH_USER_FIELDS is set to the same value as that distinguished name. For me it was `LDAP_AUTH_USER_FIELDS = { "username": "cn" }`

Depending on what name you want users to log in with, you may want to customize these attributes, and the ones in LDAP_AUTH_USER_LOOKUP_FIELDS to authenticate with the proper credentials. 

As a side note. I added a print statement directly in the open ldap function in the site packages under utils to spare my sanity when trying to just manually establish a connection from the manage.py shell command line and learn the tool.

**Comment by etianen** [comment]
Out of interest, are you using OpenLDAP or Active Directory?

There are two built-in username formatters, one for OpenLDAP and the other for Active Directory. I'd be curious why these are not suitable for your servers.

LDAP is needlessly complicated. :(

**Comment by davidkwast** [comment]
First of all, @TroyMurphy and @etianen thank you for promptly replying.

It is a OpenLDAP on a CentOS that is just configure for internal Samba usage.

I'm still trying some things here. The sync command is working but the login feature isn't. And now I'm trying to test and configure my LDAP server to permit login from any user, not just the admin.

I think you can close/reject this issue, as I am realizing that LDAP is very complicated and environment specific.

**Comment by etianen** [comment]
Have to say, I wrote this project a couple of years ago, have been maintaining it ever since, and I still don't really understand LDAP!

A few months ago I had to integrate a MediaWiki install with LDAP via PHP's LDAP library. 8 hours of hell!

Authentication should not be this complicated. LDAP is absurd. Sure, we have to integrate with it, but I have yet to find a way to make it "just work".
