### ISSUE TITLE
Update for compatibility with ldap3 2.x release

### ISSUE THREAD

**Issue by ericgreveson** [etianen/django-python3-ldap#53]
This project depends on ldap3 (https://pypi.python.org/pypi/ldap3) - version 2 of which was released on 27th Oct 2016. This incorporates the following warning:

> In version 2 of ldap3 some default values have been changed and the ldap3 namespace has been decluttered, removing redundant constants (look at the changelog for details). Also, the result code constants were moved to ldap3.core.results and the ldap3 custom exceptions were stored in ldap3.core.exceptions. If you experience errors in your existing code you should rearrange the import statements or explicitly set the defaults to their former values.

I believe that this means that django-python3-ldap won't work with ldap3>=2.0 - it would be great if it was updated to take advantage of the latest version!

**Comment by etianen** [comment]
That is correct, django-python3-ldap needs updating to work with ldap3>=2.0.

I'd be happy to take a pull request for this.

Alternatively, I'll look at it when I have time. It's not a massive
priority, as it works with ldap3<2.0, so my users can log in, but it's
always good to keep dependencies updated, so would get done eventually!

**Comment by ericgreveson** [comment]
OK, great - if I get a chance to look at this in the next week or two, I'll make sure I create a pull request. Otherwise we can wait a bit too!

**Comment by etianen** [comment]
Take a look at the master branch, this should be done.

**Comment by ericgreveson** [comment]
Thanks, that's great - will have a look soon!
