### ISSUE TITLE
Multiple search base support?

### ISSUE THREAD

**Issue by WeakLemonDrink** [etianen/django-python3-ldap#57]
First thanks for making this app available, its great. I've been looking at the code to see how I would implement multiple search bases? Would I have to create a custom backend subclassing a lot of the django_python3_ldap code for each search base like this in my `settings.py`:

`AUTHENTICATION_BACKENDS = ('my_custom_auth.auth.UKLDAPBackend',
	'my_custom_auth.auth.DELDAPBackend', 'django.contrib.auth.backends.ModelBackend')`

Referencing different search bases e.g.

`LDAP_AUTH_UK_SEARCH_BASE = 'ou=engineering,ou=united kingdom,ou=my company users,dc=my company,dc=global,dc=corp'
LDAP_AUTH_DE_SEARCH_BASE = 'ou=engineering,ou=germany,ou=my company users,dc=my company,dc=global,dc=corp'`

Or is there something already built in that would support multiple search bases? I can't see something immediately obvious but I may well have missed it.

**Comment by etianen** [comment]
The search is recursive, so if you specify a single search base higher up the tree that includes all search bases, it should work.

**Comment by WeakLemonDrink** [comment]
OK thanks I'll try that :)

**Comment by etianen** [comment]
Note: The master branch has just been updated to use the ldap3 2.x release,
so you might want to check out the latest code.
