### ISSUE TITLE
Authenticate with a field that is not set as the custom User model's USERNAME_FIELD

### ISSUE THREAD

**Issue by Ernest0x** [etianen/django-python3-ldap#6]
Hello @etianen,

I have a custom User model like this:

```python
class User(AbstractBaseUser, PermissionsMixin):
    identifier = models.UUIDField(default=uuid.uuid4, unique=True)
    email = models.EmailField(max_length=255, unique=True, null=True)

    USERNAME_FIELD = 'identifier'
```

I want to authenticate to ldap using the 'email' field instead of the 'identifier' field which is set in USERNAME_FIELD. I do not want to change USERNAME_FIELD because other authentication backends will use the 'identifier' field for authentication. By looking in the code, it seems that I have to manipulate  the resolve_user_identifier function to do this. So, do you think that an LDAP_AUTH_RESOLVE_USER_IDENTIFIER setting for passing a custom callable similar to LDAP_AUTH_CLEAN_USER_DATA is a good idea? Or is there another way?

**Comment by etianen** [comment]
Try setting LDAP_AUTH_USER_LOOKUP_FIELDS = (“email”,) in your settings.py file.

Should do the trick.
