### ISSUE TITLE
compatibility django 1.11

### ISSUE THREAD

**Issue by aritas1** [etianen/django-python3-ldap#61]
hey,

the changes introduced by this ticket raises some errors with the auth.py/ldap.py. The request parameter is now populated down to the authenticate() function => *args now contains now the request:
https://code.djangoproject.com/ticket/25187

I think the function signature mismatch between the ldap.py authenticate() and auth.py authenticate() causes the problems.

**Comment by etianen** [comment]
Good spot!

I'll happily take a pull request to fix this, or look into it myself when Django 1.11 is a bit more stable.
