### ISSUE TITLE
module 'ldap3' has no attribute 'SEARCH_SCOPE_WHOLE_SUBTREE'

### ISSUE THREAD

**Issue by jeffclay** [etianen/django-python3-ldap#62]
I'm getting the error below. This is a new setup. I'm very new to Django so it's very possible I'm doing something wrong. The error occurs during login. I did a packet capture and I can see that the auth is binding properly, so I would say this error happens after ldap binding.

Using:
Python 3.5.3
Django 1.10.6
ldap3 2.2.1
django-python3-ldap 0.9.11

```
Traceback (most recent call last):
  File "C:\Users\jeff\django-ccp\lib\site-packages\django_python3_ldap\ldap.py", line 137, in connection
    yield Connection(c)
  File "C:\Users\jeff\django-ccp\lib\site-packages\django_python3_ldap\ldap.py", line 162, in authenticate
    return c.get_user(**kwargs)
  File "C:\Users\jeff\django-ccp\lib\site-packages\django_python3_ldap\ldap.py", line 101, in get_user
    search_scope = ldap3.SEARCH_SCOPE_WHOLE_SUBTREE,
AttributeError: module 'ldap3' has no attribute 'SEARCH_SCOPE_WHOLE_SUBTREE'
```

Here are my settings:
```
LDAP_AUTH_URL = "ldap://ip.addr:389"

LDAP_AUTH_USE_TLS = False

LDAP_AUTH_SEARCH_BASE = "MY-OU-PATH"

LDAP_AUTH_OBJECT_CLASS = "person"

LDAP_AUTH_USER_FIELDS = {
    'username': 'sAMAccountName',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
}

LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "corp"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
```

**Comment by jeffclay** [comment]
Found the following information on deprecated constants.

http://ldap3.readthedocs.io/changelog.html?highlight=SEARCH_SCOPE_WHOLE_SUBTREE

I modified lines 78 and 101 of ldap.py accordingly and the error went away. I'm not sure if there are other changes needed to comply with current constants names.

**Comment by jeffclay** [comment]
Also, of note, after loggin in, the django db auth_user only contained the first letter of attributes mapped via "LDAP_AUTH_USER_FIELDS".

**Comment by etianen** [comment]
Try using version 0.9.12, which I've just released. It contains a fix which has been lurking in master for a while.
