### ISSUE TITLE
All LDAP_AUTH_USER_FIELDS contain only first character of attribute

### ISSUE THREAD

**Issue by jeffclay** [etianen/django-python3-ldap#63]
Using version 0.9.12 and ldap3 version 2.2.0, authentication works, however, when the user is created in djangodb auth_user table the fields only contain the first letter of each attribute.

**Comment by etianen** [comment]
That is very unusual. I've never encountered that behavior. Unfortunately, LDAP servers and the underlying python ldap library are both very inconsistent, so weird stuff like this happens all the time. 😒 

I've uploaded a possible fix to master. Please check it out and let me know if it fixes your issue.

**Comment by shizacat** [comment]
Hi, I have same the problem. You code helped!
ldap3==2.2.0
Django==1.10.6

**Comment by Gistavo** [comment]
Same problem here. Solved now.
Thanks!

**Comment by sysmoon** [comment]
same problem. i also solved now.
thanks.

**Comment by sysmoon** [comment]
hi i have same problem, and solved now.
but i have another issue  i can't login admin page. 
i executed python manage.py ldap_promote 'username'.
and checked user set to as a superuser=1, staff=1 in my DB

i think it's related issue (https://github.com/etianen/django-python3-ldap/issues/12)
how can i solve this?
below is my env.

[my venv]
Django==1.10.6
django-python3-ldap==0.9.12
ldap3==2.2.0

[my settings.py]
# The URL of the LDAP server.
LDAP_AUTH_URL = "ldap://10.32.130.11:389"
LDAP_AUTH_USE_TLS = False
LDAP_AUTH_SEARCH_BASE = "ou=pearlabyss,dc=pearlabyss,dc=com"
LDAP_AUTH_OBJECT_CLASS = "person"

# User model fields mapped to the LDAP
# attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = 'abyss'

LDAP_AUTH_CONNECTION_USERNAME = 'pearldev'
LDAP_AUTH_CONNECTION_PASSWORD = '********'

**Comment by etianen** [comment]
This is now available as v0.9.13
