### ISSUE TITLE
Format user: {username}@{domain}

### ISSUE THREAD

**Issue by shizacat** [etianen/django-python3-ldap#66]
Maybe you add this code. 
In my case, he helped.

```python
def format_username_active_directory_dog(model_fields):
    username = model_fields["username"]
    if settings.LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN:
        username = "{username}@{domain}".format(
            domain=settings.LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN,
            username=username,
        )
    return username
```

**Comment by PeterChu** [comment]
In my case the username format for the system Active Directory is:

`username = "CN={username},{domain}".format(
    username=username,
    domain=settings.LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN,
)`

I think there are about 4 or 5 styles for username for Active Directory. It would be great if we can have a SETTING for it.

**Comment by etianen** [comment]
There is a setting for it, you just have to create a custom function for it. :)

Maybe another setting for the separator is called for? What separators are possible? Are any of the username formats not composed of a username, a separator and a domain?

(And why is LDAP so needlessly complicated?!)

**Comment by etianen** [comment]
The email-style login is now supported in master. Please try it out.

https://github.com/etianen/django-python3-ldap#microsoft-active-directory-support

**Comment by shizacat** [comment]
Thank you very much!
