### ISSUE TITLE
Add a setting for generic filtering of LDAP entries

### ISSUE THREAD

**Issue by Ernest0x** [etianen/django-python3-ldap#7]
Currently there is no setting for generic filtering of LDAP entries. It is only possible to filter for the object class, but needs would vary. For example, one may want to filter the search only to users that are members of a specific group.

**Comment by etianen** [comment]
Does LDAP_AUTH_SEARCH_BASE not work for you?

Otherwise, how is group membership defined in your LDAP database?

**Comment by Ernest0x** [comment]
I have multiple group entries under "ou=Group,dc=example,dc=org" and each entry has multiple "member" attributes pointing to people in "ou=People,dc=example,dc=org". A memberOf overlay exists that allows filtering users for group membership.

Of course, there are other use cases for filtering users (for example, filtering only those with a specific attribute value (e.g. enabled=TRUE)).

**Comment by etianen** [comment]
Yours sounds like a tricky use-case to support, as it involved looking up a secondary entry in the LDAP directory that references the primary user. Have you got any examples of how other LDAP libraries implement this?

**Comment by Ernest0x** [comment]
The [memberOf overlay](http://www.openldap.org/doc/admin24/overlays.html#Reverse Group Membership Maintenance) does the trick so that a single ldap query will do the job.

**Comment by Ernest0x** [comment]
I have just pushed pull request #27 to add support for this.

**Comment by etianen** [comment]
Check out this branch, which adds in a setting for a function to customise the search fields:

https://github.com/etianen/django-python3-ldap/tree/configure-user-identifier

The setting you want is: LDAP_AUTH_CLEAN_SEARCH_DATA

In your case, I'd implement LDAP_AUTH_CLEAN_SEARCH_DATA as something like:

``` py
from django_python3_ldap.utils import clean_search_data

def my_clean_search_fields(ldap_fields):
    ldap_fields = clean_search_data(ldap_fields)
    ldap_fields["memberOf"] = "foo"
    return ldap_fields
```

**Comment by Ernest0x** [comment]
Unfortunately, that would not work with repeating attributes and also does not allow boolean operations other than 'AND', which are pretty common in many use cases.  The 'memberOf' is a good example. You may want users to be members of group 'A' OR group 'B' OR group 'C', or you may want users to be members of both group 'A' AND group 'C' but NOT group 'B'.

I really don't see any reason not to use LDAP search filter syntax directly. Most major applications integrating with LDAP (e.g. mail servers) do exactly that.

**Comment by etianen** [comment]
I think that it's the mixing of ldap search syntax with an otherwise pythonic process that feels wrong. At the moment, the search filter is built up using fields from a number of settings, where model fields are mapped to ldap fields, and a unique user identifier built up, without having to worry about escaping or syntax. Then again, creating a python DSL for building arbitrary LDAP queries falls into the ORM trap quite rapidly.

Maybe allowing a backing in LDAP_AUTH_CLEAN_SEARCH_DATA where you can do something like this:

``` py
from django_python3_ldap.utils import clean_search_data

def my_clean_search_fields(ldap_fields):
    ldap_fields = clean_search_data(ldap_fields)
    ldap_fields["__raw__"] = "whatever you want"
    return ldap_fields
```

The raw query would be AND'd onto the rest of the automatically-generated query.

**Comment by Ernest0x** [comment]
I think it is cleaner and more intuitive to have a specific setting for providing an extra filter that it is AND'ed to the final filter. That's why I called that setting LDAP_AUTH_SEARCH_EXTRA_FILTER in my pull request. It's optionally given for finer filtering of users not only based on the user mapping settings, but also based on extra, application-specific criteria (group membership, etc.).

I understand that it may seem there is some inconsistency between syntaxes of settings that will be used for final filtering of users. However, if we look at the settings from a user's perspective, we may see that we actually need settings for 2 different purposes. First, we need settings for user and user attribute mapping with the simpler way to express that being it how it is done now: a pythonic mapping. Second, we need some setting for extra, application-specific filtering and the simpler way to express that would be in the LDAP filter syntax. I think that it's quite clear that users will be looked up at LDAP based on the mapping settings and, if needed, filtered further down based on an extra filtering setting.

**Comment by etianen** [comment]
I don't think that LDAP_AUTH_SEARCH_EXTRA_FILTER should be a string,
though. It should be a function, in case the user wants the filter to be
based on a dynamic value.

If it's a function, then I don't see the harm with including it in the
LDAP_AUTH_CLEAN_SEARCH_DATA
function.

**Comment by Ernest0x** [comment]
> I don't think that LDAP_AUTH_SEARCH_EXTRA_FILTER should be a string,
> though. It should be a function, in case the user wants the filter to be
> based on a dynamic value.

I agree. It should be a function.

> If it's a function, then I don't see the harm with including it in the
> LDAP_AUTH_CLEAN_SEARCH_DATA
> function.

The only thing is that we would have two settings that both do about the same thing. So, I am thinking of another solution. What about making LDAP_AUTH_CLEAN_SEARCH_DATA return a list of the actual ldap filter strings that will be AND'd for the final filter, so that one could append a custom filter to that list. For example:

```
    def my_clean_search_fields(ldap_fields):
        # Pythonic way to add fields to filter:
        ldap_fields["enabled"] = "TRUE"
        ldap_filters = clean_search_data(ldap_fields) # returns list of strings in ldap filter syntax

        # Optionally, append custom filter for more advanced filtering:
        MY_CUSTOM_FILTER = '(|(memberOf=groupA)(memberOf=GroupB))'
        ldap_filters.append(MY_CUSTOM_FILTER)

        return ldap_filter
```

**Comment by etianen** [comment]
Hmm, I can see that working. The setting should probably be renamed
LDAP_AUTH_FORMAT_SEARCH_DATA, but that's fine.

**Comment by etianen** [comment]
Take a look now:

**Comment by etianen** [comment]
https://github.com/etianen/django-python3-ldap/tree/configure-user-identifier#custom-user-filters

**Comment by Ernest0x** [comment]
That looks very good! Thanks.

**Comment by etianen** [comment]
This is now in release 0.9.7

**Comment by mnach** [comment]
Thank you for release, Dave !

I will replace my "dev"-build in our project.

Also, our clients are highly satisfied with ability of logging into the site with their domain credentials.

**Comment by etianen** [comment]
Excellent! When I wrote it I had basically no idea what LDAP was, and I
still believe it to be a stupidly complicated approach to writing what's
essentially a user database. Still, centralised auth, without relying on
something 3rd party like Google or Twitter, is very nice indeed. I just
wish we'd standardised on a better system than LDAP...

**Comment by FlipperPA** [comment]
To know LDAP is to despise LDAP, but its a necessary evil. Thanks very much for your efforts, Dave, please know they are very much appreciated.

**Comment by jjagielka** [comment]
About custom search filters. Search only for those which has the mail set.
```
    ldap_fields["mail"] = "*"
    # Call the base format callable.
    search_filters = format_search_filters(ldap_fields)
```
This won't produce `(mail=*)` as `*` will get escaped by `format_search_filters` and we got `(mail=\2A)`

**Comment by etianen** [comment]
You'll need to use the custom format_search_filters method:

```
# settings.py
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "path.to.your.custom_format_search_filters"

# pay/to/your.py
from django_python3_ldap.utils import format_search_filters

def custom_format_search_filters(ldap_fields):
    # Call the base format callable.
    search_filters = format_search_filters(ldap_fields)
    # Advanced: apply custom LDAP filter logic.
    search_filters.append("(mail=*)")
    # All done!
    return search_filters
```
