### ISSUE TITLE
can't map ldap3 search to django-python3-ldap config

### ISSUE THREAD

**Issue by grudelsud** [etianen/django-python3-ldap#70]
hi

1st things 1st: thank you for sharing this codebase with the community!

I can't seem to find the right configuration for the django plugin though, I have a working ldap3 example and trying to match it in my settings but always getting

`LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C0903A8, comment: AcceptSecurityContext error, data 52e, v1db1 - bindResponse - None`

the following is a working example of search I'm doing with ldap3

```python
from ldap3 import Server, Connection, ALL

print('### SERVER')
server = Server('host.group.domain.com', get_info=ALL)

print('### CONNECT')
conn = Connection(
    server,
    'CN=ldap_user,OU=SERVICE,OU=100 Common Services Objects,OU=Common Services and Applications,DC=group,DC=domain,DC=com',
    'ldap_password',
    auto_bind=True)

print('### SEARCH')
conn.search('DC=group,DC=domain,DC=com', '(&(sAMAccountName=username_search)(objectclass=user))')

print('### ENTRIES')
print([e for e in conn.entries])
```

I tried, among other combinations, the following

```python
LDAP_AUTH_URL = 'ldap://host.group.domain.com:389'

LDAP_AUTH_SEARCH_BASE = 'DC=group,DC=domain,DC=com'

LDAP_AUTH_USER_FIELDS = {
    'username': 'sAMAccountName',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail'
}

LDAP_AUTH_CONNECTION_USERNAME = 'CN=ldap_user,OU=SERVICE,OU=100 Common Services Objects,OU=Common Services and Applications,DC=group,DC=domain,DC=com'
LDAP_AUTH_CONNECTION_PASSWORD = 'ldap_password'

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
```

but always getting the invalid credential error. could you give a quick hint please? I'd be happy to help writing a bit of documentation if this use case is relevant for you

many thanks!

**Comment by grudelsud** [comment]
ok, I've studied the code a bit and now I see what's going on here:

when `django_python_ldap3.ldap.connection` executes, it tries to create an ldap3 connection to the server using the username and password I passed in the authentication form, but my AD server doesn't allow to do so as I need to use another user (`(ldap_user, ldap_password)` in my example above) to run the search. 
any ideas on how to overcome this problem and creating the connection with user credentials that are not the ones used for auth?

many thanks in advance

**Comment by etianen** [comment]
For django-python3-ldap to authenticate, the user you bind with needs permissions to read it's own details from the LDAP server. If yours isn't set up to allow this, then you shall indeed run into problems.

Is it possible to bind() as another user after performing the initial authentication? If so, then it shouldn't be too much work to add to this library. Otherwise, you'd need two different LDAP connections, which seems excessive!

**Comment by grudelsud** [comment]
I must confess that after tinkering a bit with the authentication class and function, I rolled back to a different django library that seems to work fine by specifying different parameters for bind and auth. thanks for getting back on this though, I'll close the issue (although it could probably be a nice feature to have)

**Comment by busla** [comment]
I agree, this would be a nice feature. I can only log in as the `LDAP_AUTH_CONNECTION_USERNAME` user since our server is not configured so that all users can read their own details.

**Comment by etianen** [comment]
Try the latest commit from master. `LDAP_AUTH_CONNECTION_USERNAME` and `LDAP_AUTH_CONNECTION_PASSWORD` are now used to query the LDAP databae after authentication.

**Comment by binteezyy** [comment]
Hi. 

I'm trying to lookup for a specific user in the LDAP.

I have tried his code and the authentication was successful. However, it returns me this error:

**search() missing 1 required positional argument: 'search_filter'**

and it points to the line:

**conn.search('_search-base-here_')**

I'm still searching for ways to lookup for a certain user using a directory name for LDAP. I bumped to this  issue and wondering if it was successful. I am open to suggestion with ways on how can I **lookup a specific person on LPAD**.

**Comment by sonicblind** [comment]
@binteezyy 

```
conn.search(
    search_base=settings.LDAP_AUTH_SEARCH_BASE,
    search_filter=format_search_filter(kwargs),
    search_scope=ldap3.SUBTREE,
    attributes=ldap3.ALL_ATTRIBUTES,
    get_operational_attributes=True,
    size_limit=1,
)
```

For more info have a look at [LDAP Search](https://ldap3.readthedocs.io/searches.html) signature.

**Comment by binteezyy** [comment]
@sonicblind 

Your answer has helped me a lot. I haven't seen that link before or maybe I'm just too dumb. Thank you so much @grudelsud @sonicblind @etianen 

Here is my final snippet for **querying a specific user and a specific attribute from LDAP with a directory name connected to the User**

        ```
from ldap3 import Server, Connection, SUBTREE,
from django.conf import settings

        server_url = settings.LDAP_AUTH_URL
        connection_account = str(settings.LDAP_CN) + ',' + str(settings.LDAP_AUTH_SEARCH_BASE)
        connection_password = str(settings.LDAP_AUTH_CONNECTION_PASSWORD)

        server = Server(server_url, get_info=ALL)
        
        conn = Connection(
        server,
        connection_account,
        connection_password,
        auto_bind=True)

        conn.search(
            search_base = current_user.**directoryName**,
            search_filter = '(objectClass=user)',
            search_scope = SUBTREE,
            types_only=False,
            attributes=['mail'],
            get_operational_attributes=True,
            size_limit=1,
            )

       print(conn.response[0]['attributes']['mail'])
```
