### ISSUE TITLE
example of creating groups and permissions in django model form LDAP

### ISSUE THREAD

**Issue by arif-hanif** [etianen/django-python3-ldap#74]
is there a way to create groups in the django model based on LDAP settings? Does anyone have any example or could point in right direction if its possible.

**Comment by etianen** [comment]
The LDAP_AUTH_CLEAN_USER_DATA and LDAP_AUTH_SYNC_USER_RELATIONS settings
are your friends here. Check out the docs here:

https://github.com/etianen/django-python3-ldap#available-settings

**Comment by etianen** [comment]
The password is an unusable password, which forces the user to login via LDAP rather than any other authentication backends (e.g. ModelBackend).

**Comment by pitchblack408** [comment]
Hi,  I have 2 Active Directory groups, 1 for admin and another for users.  I can't change the schema, so I am not able to add more attributes.  How can I create users and assign them to the seperate groups in django?  I know you say that I should use the settings above.  But I don't understand those stub methods should work.  I haven't seen any examples online either.

**Comment by etianen** [comment]
Hmm. That is tricky. The auth backend doesn't get any information about the path the user was loaded from in LDAP. If that information isn't stored on attributes, it's not accessible.

The easy solution, if you have a limited number of users that don't change much, is to handle assigning them permissions manually in the django admin, once they've been synced across.

Otherwise, this library will have to have some non-trivial changes to support that use-case.

**Comment by pitchblack408** [comment]
Can you give me some examples on how LDAP_AUTH_CLEAN_USER_DATA and LDAP_AUTH_SYNC_USER_RELATIONS are supposed to be changed for the current use cases it was intended to support?

**Comment by pitchblack408** [comment]
Is memberOf treated as a attribute, maybe there is a way to create relationships based on that?

**Comment by pitchblack408** [comment]
After looking at your test cases, I was able to come up with this below.  What do you think? Is this how you intended this to be used?

def sync_all_user_group_relations(user, data):
    
    ldap_groups = list(data.get('memberOf', ()))
    for group in ldap_groups:
        if group == 'CN=InternalBilling-Users,OU=EC-Users,OU=Groups,DC=abc,DC=abc,DC=com':
            g = Group.objects.get(name='Billing clerks')
            user.is_staff=True
            user.save()
            g.user_set.add(user)
        elif group == 'CN=InternalBilling-Admin,OU=EC-Users,OU=Groups,DC=abc,DC=abc,DC=com':
            g = Group.objects.get(name='Billing admins')
            user.is_staff=True
            user.save()
            g.user_set.add(user)

**Comment by etianen** [comment]
Yes, that's exactly how that method was intended to be used!

**Comment by JimInCO** [comment]
Would it be useful to include an example like this in the documentation?

**Comment by etianen** [comment]
I'm not sure. There are so many weird and wonderful ldap setups out there,
I worry that we'll end up drowned in examples.

**Comment by avocadosarelife** [comment]
@pitchblack408 would you mind sharing your Group class? My django application is working using this LDAP authentication , but I'm having trouble giving different accesses to different LDAP groups.
