### ISSUE TITLE
Part of the code for version 9.14 is not in the - pypi.python.org

### ISSUE THREAD

**Issue by p-demis** [etianen/django-python3-ldap#77]
# If the settings specify an alternative username and password for querying, rebind as that.
    if (
        (settings.LDAP_AUTH_CONNECTION_USERNAME or settings.LDAP_AUTH_CONNECTION_PASSWORD) and
        (
            settings.LDAP_AUTH_CONNECTION_USERNAME != username or
            settings.LDAP_AUTH_CONNECTION_PASSWORD != password
        )
    ):
        try:
            c.rebind(
                user=format_username({"username": settings.LDAP_AUTH_CONNECTION_USERNAME}),
                password=settings.LDAP_AUTH_CONNECTION_PASSWORD,
            )
        except LDAPException as ex:
            logger.info("LDAP rebind failed: {ex}".format(ex=ex))
            yield None
            return

**Comment by etianen** [comment]
It's in the master branch, provisionally under 0.10.0.
