### ISSUE TITLE
FR: Show errors when User model does not pass validations

### ISSUE THREAD

**Issue by nathanperkins** [etianen/django-python3-ldap#83]
I had some trouble implementing this earlier because only one of the users from my search OU was being saved out of hundreds. I thought it was an issue with the AD module, but it was because I wasn't pulling the correct username field (sAMAccountName) and therefore my users were being created without usernames, which didn't pass validations. This was with logging turned on. 

Maybe some extra messages would help?

It might be nice to indicate when a user is added, when a user is updated, when a user was checked but no updates needed, and when a user fails to pass validations.

That said, thanks for the tool! It's awesome :)

**Comment by etianen** [comment]
I think you'll find the master branch has much more verbose logging in.

**Comment by etianen** [comment]
(Any more suggestions for useful logs appreciated! The initial setup phase for this library is painful!)
