### ISSUE TITLE
FR: Only update modified users

### ISSUE THREAD

**Issue by busla** [etianen/django-python3-ldap#84]
When syncing users on regular intervals, let´s say once a day, it seems that user sessions get destroyed.

Therefore, all users need to re-login after an *ldap_sync*

Would be great if we could only update users that have changed to keep as many logged-in sessions as possible.

**Comment by busla** [comment]
Here is an idea:

https://github.com/busla/django-python3-ldap/commit/17fc7fa609bfc1ee0bb2de2867a21e3f68c221a1

**Comment by etianen** [comment]
I don't think that code will update modifed users. It'll only set the
details on first user creation.

I think that the problem is caused by setting the password field to a new
unusable password.

https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/utils.py#L64

If this was only done on first user creation, I think we'd be sorted.

**Comment by busla** [comment]
As described in the commit message, it will pass the existing user object to the sync function which should handle the field comparison.

**Comment by etianen** [comment]
I understand the intention, but I don't think the code does what you think
it will. I've added some comments to illustate.

**Comment by busla** [comment]
Correct, it will not modify updated users, since it could be done in the sync_function.

If the user does exist, it´s passed to the sync_function for updating.

**Comment by busla** [comment]
But yeah, `User.objects.update_or_create` is unnecessary, could be `User.object.create_user`:

https://docs.djangoproject.com/en/1.11/topics/auth/default/#creating-users

.. or similar.

**Comment by etianen** [comment]
The master branch now contains an update that should avoid breaking user sessions with ldap_sync_users.

e828798e86227f273f776896ac5382943a44b50c

**Comment by busla** [comment]
Thanks :smile:
