### ISSUE TITLE
django-python3-ldap authentication Issue on Admin Page

### ISSUE THREAD

**Issue by JaronHamburg** [etianen/django-python3-ldap#85]
I am trying to get ldap authentication to work on the Django Admin Page. I am using the below configuration

    AUTHENTICATION_BACKENDS = (
        'django_python3_ldap.auth.LDAPBackend',
        )
    
    # The URL of the LDAP server.
    LDAP_AUTH_URL = "ldap://dc.prod.company.com"
    
    LDAP_AUTH_CONNECTION_USERNAME = "username@americas.corp.local"
    LDAP_AUTH_CONNECTION_PASSWORD = "Password1"
    
    LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
    LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "AMERICAS"
    
    LDAP_AUTH_SEARCH_BASE = "ou=unix,ou=accounts,ou=inetgpo,dc=americas,dc=corp,dc=local"
    
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
        },
        "loggers": {
            "django_python3_ldap": {
                "handlers": ["console"],
                "level": "DEBUG",
            },
        },
    }

But I keep getting the same error, even after running: 

    ./manage.py ldap_promote username

Error:

    Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.

I know that the authentication is working because when i put in an incorrect username/password I get the following:

    [17/May/2017 08:23:10] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1650
    LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C090334, comment: AcceptSecurityContext error, data 52e, vece - bindResponse - None
    [17/May/2017 08:23:20] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1812

When the correct username & password is entered I just get:

    [17/May/2017 08:24:34] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1812
But still this error on the front end:

    Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.

What other logging can I add to see what is happening? Is LDAP Authentication expected to work on the django admin page http://127.0.0.1:8000/admin/login/?next=/admin/ ?

**Comment by etianen** [comment]
What is stored in the username field of your model?

**Comment by JaronHamburg** [comment]
I have one user permissioned as staff and superuser:
Username: 87302K
Password: Password1

I can see there is an ldap authentication working, but the page just doesn't login. If i type Password2 authentication fails:

LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C090334, comment: AcceptSecurityContext error, data 52e, vece - bindResponse - None

If i turn off the below I can login fine:

AUTHENTICATION_BACKENDS = (
    'django_python3_ldap.auth.LDAPBackend',
    )

**Comment by etianen** [comment]
So, in the admin login page, you are entering the following information:

Username: 87302K
Password: Password1

And in the database, there is an admin user with the following fields:

Username: 87302K
Password: Password1
Is staff: True
Is superuser: True
Is active: True

And in LDAP, there is a user in the following location:

ou=unix,ou=accounts,ou=inetgpo,dc=americas,dc=corp,dc=local

And the user has the following fields:

uid: 87302K

Incidentally, if you update to use the master branch, there is even more
verbose logging that will probably shed some light on this.

**Comment by JaronHamburg** [comment]
I will try and upgrade to your master branch but can I get this version from pip?
When i download the 0.9.14 tar and run python setup.py install it just creates a .egg file with no django-python3-ldap folder?

**Comment by JaronHamburg** [comment]
Ok I managed to upgrade to your master branch. Now I am getting:
[17/May/2017 13:28:13] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1809
LDAP connect succeeded
LDAP user lookup failed

So there is something wrong with my Search of the LDAP database. What should I look at next?

**Comment by etianen** [comment]
The relevant settings for search are:

LDAP_AUTH_SEARCH_BASE
LDAP_AUTH_OBJECT_CLASS
LDAP_AUTH_USER_FIELDS

The docs are here:
https://github.com/etianen/django-python3-ldap#available-settings

**Comment by FlipperPA** [comment]
I'll chime in here with a "me too." Since upgrading from Django 1.9 to 1.11, and upgrading `django-python3-ldap`, I'm unable to log in. If I go into verbose mode:

`WARNING:django_python3_ldap.ldap:LDAP rebind failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - None - bindResponse - None`

However, I'm sure I'm entering the correct credentials (saved in LastPass, still working on the old 1.9 version of the site).

My settings:

    LDAP_AUTH_CONNECTION_PASSWORD = '********************'
    LDAP_AUTH_CONNECTION_USERNAME = 'authenticator'
    LDAP_AUTH_OBJECT_CLASS = 'shadowAccount'
    LDAP_AUTH_SEARCH_BASE = 'ou=People,dc=foo,dc=bar,dc=upenn,dc=edu'
    LDAP_AUTH_URL = 'ldaps://foo-ldap.bar.upenn.edu:636'
    LDAP_AUTH_USER_FIELDS = {'username': 'uid'}
    LDAP_AUTH_USER_LOOKUP_FIELDS  = ('username',)
    LDAP_AUTH_USE_TLS = True

New (Broken) Versions: Django==1.11.2, django-python3-ldap==0.10.0, ldap3==1.3.3
Previous Working Versions: Django==1.9.x, django-python3-ldap==0.9.5, ldap3==1.3.3

I've tried `pip install -e` on a few of the previous commits, but with no luck so far. I'll dig deeper but wanted to get this information in in case it helps.

**Comment by FlipperPA** [comment]
After doing some digging I've found the issue, but could use some advice on how you'd like to fix it.

The `format_username` function is taking the `LDAP_AUTH_CONNECTION_USERNAME` and appending the DN, outputting:

`uid=authenticator,ou=People,dc=foo,dc=bar,dc=upenn,dc=edu`

However, for the LDAP service authenticator account, we actually connect with:

`cn=authenticator,dc=wrds,dc=wharton,dc=upenn,dc=edu`

**Comment by etianen** [comment]
You can overrride the format_username function with your own
implementation, and do what you need. That's what the
LDAP_AUTH_FORMAT_USERNAME setting is for.

I'm confused about why this broke for you in the latest release, though.
The logic for authentication is:

1. LDAP bind using the supplied username and password. Abort if fail.
2. If LDAP_AUTH_CONNECTION_USERNAME is set, rebind with that.
3. Query the ldap database for the user details. If not found, abort.

Step 2 is what's changed in the new release.

However, the whole point of LDAP_AUTH_CONNECTION_USERNAME is that it should
specify an account for querying the ldap database. It's also used by the
ldap_sync_users management command. It should be able to access all users
in the system.

**Comment by rgs258** [comment]
LDAP_AUTH_FORMAT_USERNAME  seems to do the trick. So, we have this now:
`import logging
from django.conf import settings
from django_python3_ldap import utils as dj_ldap_utils

logger = logging.getLogger(__name__)

def format_username(model_fields):
    """
    Formats a user identifier into a username suitable for binding to WRDS' OpenLDAP server.
    """

    if 'username' in model_fields and model_fields['username'] == settings.LDAP_AUTH_CONNECTION_USERNAME:
        formatted_username = f'cn={settings.LDAP_AUTH_CONNECTION_USERNAME},dc=wrds,dc=wharton,dc=upenn,dc=edu'
    else:
        formatted_username = dj_ldap_utils.format_username_openldap(model_fields)

    logger.debug(
        f'Formatting username for WRDS LDAP, model_fields: {model_fields}, settings.LDAP_AUTH_CONNECTION_USERNAME: '
        f'{settings.LDAP_AUTH_CONNECTION_USERNAME}, (username in model_fields): {"username" in model_fields}, '
        f'model_fields["username"]: {model_fields["username"]}. Resulting formatted_username: {formatted_username}')

    return formatted_username`

Then...
`LDAP_AUTH_FORMAT_USERNAME = "config.ldap_utils.format_username"`

Thanks again for the project!

**Comment by FlipperPA** [comment]
@rgs258 It might be worth adding a minimal example of this to the README?

**Comment by etianen** [comment]
I dunno, everyone's LDAP server seems to be different.

Can you edit the wiki? Making an index page with a list of example links,
then a new page with your example on sounds like it might be good for
people to have as reference.
