### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by xTEddie** [etianen/django-python3-ldap#88]
Hello, 

My LDAP_AUTH_USER_FIELDS does not map properly the fields to the model. Here is my configuration: 

LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "cn",
    "email": "mail",
}

Everything works fine except for the last_name. The cn contains "[last_name], [first_name]". I would like to get rid of the first_name in the cn. I tried to right a django command to clean all the last_name's of the users, but I noticed that the LDAP fields gets overwritten in the user model everytime the user logs in. 

What would be the best approach to solve this issue?

**Comment by busla** [comment]
Are you sure that should be _cn_ and not _sn_? The LDAP _surname_ display-name is _sn_.

https://msdn.microsoft.com/en-us/library/ms679872(v=vs.85).aspx

**Comment by xTEddie** [comment]
It worked! nice! Thanks for the help!

**Comment by busla** [comment]
Glad to help 😄
