### ISSUE TITLE
LDAP connect succeeded - LDAP user attributes empty (new to Django)

### ISSUE THREAD

**Issue by Shasties** [etianen/django-python3-ldap#89]
I am pretty new to Django and have been tasked with setting up a self-service password reset and change application for my company. I followed along with the basic Django documentation and used their backend for authenticating users, just to see if that process would work (using Django.contrib.auth). Now I'd like to expand to actually authenticate using our AD login, so I followed your setup and changed as needed, posted below:
`AUTHENTICATION_BACKENDS=['django.contrib.auth.backends.ModelBackend',
    'django_python3_ldap.auth.LDAPBackend',
]
...
#LDAP config
LDAP_AUTH_URL="ldap://my.ad.server:389"
#LDAP_AUTH_USE_TLS=True
LDAP_AUTH_SEARCH_BASE="dc=example,dc=net"
LDAP_AUTH_FORMAT_USERNAME="django_python3_ldap.utils.format_username_active_directory_principal"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN="my.domain"
`
I have verified using the ldapsearch command that I can connect to the AD.

When I enter my credentials on the login portion of the page, I notice that in the console window it gives me "LDAP connect succeeded LDAP user attributes empty" and the page prompts me to enter in a correct username and password. 

I figure I might be doing something wrong, but I'm not exactly sure what. Another issue is that when I want to use TLS it gives me "LDAPunavailableresult - 52... error initializing SSL/TLS". I feel like that might be an issue with some sort of port forwarding on my end though? 

Thanks for putting this project together!

**Comment by etianen** [comment]
The TLS issue is probably port forwarding or LDAP server config.

The empty attributes may be a permissions setting on the LDAP server. Or
not. I'm afraid that with LDAP, there's so many ways to break it that it's
hard to know without getting dirty with the individual server. Maybe seek
assistance from the LDAP sysadmin?

**Comment by Shasties** [comment]
Thanks for responding so quickly!
I figured it was an issue with the ports, I just confirmed that. Unfortunately I'm still trying to troubleshoot the empty attributes stuff.

Just to verify, there shouldn't be any issue with using the default views from Django.contrib.auth right?

**Comment by etianen** [comment]
Reset password won't work, but login/logout will.

**Comment by Shasties** [comment]
I figured that would happen down the road, but I'm still having issues even successfully logging in users.

**Comment by Shasties** [comment]
Closing this out since I resolved the issue on my own. My fix was to change the ldap.py get_user() function with modifying code from here:
https://stackoverflow.com/questions/37847042/changing-active-directory-user-password-in-python-3-x

I'm not sure where things went wrong since it seems like your code is pretty similar, but I guess in my case something might have gotten defined improperly.
