### ISSUE TITLE
LDAP connect failed: LDAPInvalidCredentialsResult

### ISSUE THREAD

**Issue by gvizquel** [etianen/django-python3-ldap#93]
Cheers etianen. I am using django-python3-ldap, and I could actually execute the **`./manage.py ldap_sync_users`** command and I even promoted a user to admin with **`./manage.py ldap_promote <username>`**.

Now I am trying to login via admin with an ldap user that I promoted to admin, but I get the following error in the frontend:

"Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive."

This I have in my settings.py file:
```
AUTHENTICATION_BACKENDS = (
    'django_python3_ldap.auth.LDAPBackend',
)

LDAP_AUTH_URL = '192.168.1.10'
LDAP_AUTH_USE_TLS = False
LDAP_AUTH_SEARCH_BASE = 'dc=test,dc=com,dc=es,o=testldap'
LDAP_AUTH_OBJECT_CLASS = 'inetOrgPerson'
LDAP_AUTH_USER_FIELDS = {
    'username': 'uid',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
}
LDAP_AUTH_USER_LOOKUP_FIELDS = ('username',)
LDAP_AUTH_CLEAN_USER_DATA = 'django_python3_ldap.utils.clean_user_data'
LDAP_AUTH_SYNC_USER_RELATIONS = 'django_python3_ldap.utils.sync_user_relations'
LDAP_AUTH_FORMAT_SEARCH_FILTERS = 'django_python3_ldap.utils.format_search_filters'
LDAP_AUTH_FORMAT_USERNAME = 'django_python3_ldap.utils.format_username_openldap'
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = None
LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_PASSWORD = None
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}
```
This is the output of the console:
```
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - None - bindResponse - None
[19 / Jun / 2017 14:02:07] "POST / admin / login /? Next = / admin / HTTP / 1.1" 200 1814
```
I am using these versions:
```
Django == 1.11.2
Django-python3-ldap == 0.10.0
Ldap3 == 2.2.3
```

Thanks for your attention

**Comment by gvizquel** [comment]
Ok I have placed the full path to the location of the user I want to authenticate and it works. Of course this solution is not functional because there is a rather complex directory structure. 
This is the base route (not working):
`**dc=org,dc=com,dc=es,o=orgldap**`
And this is the path where the user I want to authenticate (works) is located:
`**ou=sub-department,ou=department,dc=org,dc=com,dc=es,o=orgldap**`
The question is: What should I enable in settings.py to make the search work even if there are subdirectories?

**Comment by etianen** [comment]
The problem isn't the search, since search is already recursive. The
problem is the BIND operation, which isn't recursive.

I'm afraid that my knowledge of LDAP isn't huge. Looking at the docs, there
isn't mention of how to make bind recursive:
http://ldap3.readthedocs.io/bind.html

I wonder if it's possible to put some magic wildcard into
LDAP_AUTH_SEARCH_BASE to specify "all subfolders". That's the only thing I
can thing of.

If you can find a way to do a recursive bind using the ldap3 library, I'd
be happy to add support for this to django-python3-ldap.

**Comment by gvizquel** [comment]
Thank you etianen, I will try to find something there. I will not close the case yet. If I get a solution, I'll let you know and I'll close.

**Comment by cannatag** [comment]
Hi @etianen, simple  binds cannot be recursive in ldap. You must search for the (unique) name, probably using a proxy ldap user and the perform bind with the full dn of the found user.

When binding to AD you can try the NTLM authentication that doesn't require the full dn, but only the Windows user credentials.

**Comment by etianen** [comment]
I'd happily take a pull request to add recursive search, then bind. It
won't need a new setting, as it will be backwards compatible with the
existing non-search method.

Alternatively, if your server is AD, configure as as AD as per the project
README, and you should be able to use the windows user credentials.
