### ISSUE TITLE
ldap3.Server, add get_info=ldap3.NONE ?

### ISSUE THREAD

**Issue by notespace** [etianen/django-python3-ldap#95]
Hi, got everything working nicely with django-python3-ldap, syncing, auth, against Active Directory. Nice clean integration with Django, thanks for putting this together.

Would it be possible to set get_info=ldap3.NONE when creating the ldap3.Server in ldap.py, ~line 142:  

    try:
        with ldap3.Connection(ldap3.Server(
            settings.LDAP_AUTH_URL,
            allowed_referral_hosts=[("*", True)],
    +        get_info=ldap3.NONE),
            user=username,

With the default (SCHEMA), ldap3 queries the entire schema definition from the AD/LDAP server, in our setup this results in about 1 MB of additional network traffic on every login.

Not sure if you want to use the schema info, or if there is just too a bunch of junk in our server schema haha, but I made the change locally and it seems to be working fine, and with much reduced traffic - only what's used for auth and setting up the users.

See http://ldap3.readthedocs.io/schema.html and http://ldap3.readthedocs.io/server.html, get_info parameter.

Thanks!

**Comment by etianen** [comment]
I've just pushed 2a05d41a7de819d81d212d22ed85f716196677ec to master with
this change.

Let me know if it works for you :)

**Comment by notespace** [comment]
Yes, I verified that the change worked on the current master. Thanks!
