### ISSUE TITLE
How to use custom user

### ISSUE THREAD

**Issue by moritz31** [etianen/django-python3-ldap#98]
Hey,

in the description of this project is mentioned, that the backend supports custom users.
What i need is to retrieve some additional information from our ldap(like expirydate etc.)
Therefore i've added an OneToOne-Relation which looks like this:
`class UserProfile(models.Model):
    user = models.OneToOneField(User, unique = True)
    url = models.URLField("Website", blank=True)
    company = models.CharField(max_length=50, blank=True)
    expire = models.CharField(max_length=50, blank=True)
` 

Furthermore i've added `AUTH_PROFILE_MODULE = "account.UserProfile"` to the settings.py
But when i try to login i get an 

> Invalid field name(s) for model User: 'expire'.

I've looked up the database and it seems that auth_user is untouched and don't have the field ... but in the UserProfile it is defined....
Don't know what to do here.
Maybe someone can help me there

**Comment by etianen** [comment]
This is how you specify a custom user model is Django:

https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#specifying-a-custom-user-model

What you've done is make a user *profile model*. This is an older way of
doing a similar thing, that Django still supports.

I'd generally recommend going down the custom user model route, as it
offers the best customisation options in the long run. If you need to use a
user profile model for other reasons, you can use the
LDAP_AUTH_SYNC_USER_RELATIONS setting to create and populate the profile
model.

https://github.com/etianen/django-python3-ldap#available-settings
